[Issue 10161] Fix missing LoggerFactoryPtr type.
apache/pulsar pull request #10164
Opened 2021-04-07 15:34 UTC by astifter

Fixes #10161.

### Motivation

With issue #7132 the LoggerFactoryPtr was removed in favour of relevant memory-safe(r) pointers.

This change forgot to also change the Log4Cxx implementation, fix this by returning (as with
the other LoggerFactory's) a std::unique_ptr<LoggerFactory>.

### Modifications

Change remaining LoggerFactoryPtr in Log4Cxx factory to std::unique_ptr<LoggerFactory> to conform to #7132.

### Verifying this change

  - Visual inspection of changes to comply with the ones from #7132.
  - pulsar-client-cpp builds now with USE_LOG4CXX.

2021-04-07 16:02 UTC, merlimat approved these changes

2021-04-07 16:22 UTC, astifter commented
@merlimat You wan't to base this on master?

2021-04-13 19:59 UTC, sijie approved these changes

2021-04-16 22:56 UTC, merlimat commented
@astifter Yes, the PR should be targeting master. Once it's merged then it will be cherry picked for on the 2.7 branch

2021-04-27 07:40 UTC, eolivelli commented
@astifter can you send a PR for master branch ?
I am going to cut 2.7.2 release as soon as possible, it would be a pity to not include this patch.

2021-04-27 07:40 UTC, eolivelli requested changes
I am commenting with "Request changes" in order to clarify the status of this patch

2021-04-29 19:25 UTC, astifter commented
Sorry, missed the deadline for 2.7.2, but I have rebased the change on master.

2021-05-20 09:24 UTC, Anonymitaet commented
@astifter thanks for your code work. For this PR, do we need to update docs?

2021-05-21 11:14 UTC, astifter commented
> @astifter thanks for your code work. For this PR, do we need to update docs?

No, this just fixes the compile.

2021-05-21 11:24 UTC, BewareMyPower approved these changes
LGTM

2021-05-21 11:26 UTC, BewareMyPower commented
LGTM. This bug was not exposed because CI only build cpp client with `USE_LOG4CXX=OFF`.

2021-05-21 12:45 UTC, eolivelli approved these changes

2021-05-21 12:47 UTC, eolivelli commented
I misunderstood, the name of the branch on your repo is "branch-2.7" but the target branch is "master"

2021-05-21 12:48 UTC, merged

2021-05-21 12:50 UTC, astifter commented
> I misunderstood, the name of the branch on your repo is "branch-2.7" but the target branch is "master"

Yes, sorry about that. I was working of the 2.7 branch and didn't pay attention. I couldn't change the branch easily so I kept the name. Promise to be more careful in the future.