[Broker] Close namespace clients when PulsarService is closed
apache/pulsar pull request #10196
Opened 2021-04-12 13:05 UTC by lhotari

### Motivation

The broker leaks some PulsarClient instances since the PulsarClient instances created in NamespaceService don't get closed.

### Modifications

Add handling for closing PulsarClient instances created in NamespaceService. A similar logic for closing is used as there is currently for [closing the PulsarClients of replication clients](https://github.com/apache/pulsar/blob/5fcd0d18f8b33474fd8fb5faa3e2330fd88c554a/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L680-L686).

2021-04-12 13:19 UTC, eolivelli requested changes

2021-04-12 13:19 UTC, eolivelli commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
> +    public void close() throws IOException {
Can we remove the 'throws' clause?
We can also move to AutoCloseable instead of Closeable

2021-04-12 19:45 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-12 19:46 UTC, merlimat approved these changes

2021-04-12 21:00 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 03:00 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 05:29 UTC, 315157973 approved these changes
LGTM

2021-04-13 06:03 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 06:26 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 07:04 UTC, eolivelli approved these changes
LGTM

2021-04-13 10:42 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 10:55 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 11:12 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 11:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 12:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 18:00 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 18:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-13 19:53 UTC, sijie approved these changes

2021-04-14 00:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-14 04:18 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-14 07:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-14 08:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-14 09:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-14 17:16 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-14 21:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-15 00:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-15 03:15 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-15 09:41 UTC, merged