[Tests] Remove ".atMost" definitions for Awaitility in most cases
apache/pulsar pull request #10344
Opened 2021-04-23 14:07 UTC by lhotari

### Motivation

Some tests are flaky because the time limits set for Awaitility are too strict.
It's better to avoid specifying the time limit and rely on the default value that is 10 seconds.
This improves the readability of the test.

### Modifications

- drop `.atMost` definitions used to configure Awaitility in tests.

2021-04-23 15:34 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-23 17:12 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-04-23 17:55 UTC, eolivelli approved these changes
Lgtm

2021-04-24 04:51 UTC, michaeljmarshall requested changes
Looks good to me, other than some comments that need to be updated.

2021-04-24 04:51 UTC, michaeljmarshall commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
>          // Wait at most 2 seconds for sub1's message to expire.
It's probably worth updating this comment, as the wait is now the default setting instead of the specified 2 seconds.

2021-04-24 04:51 UTC, michaeljmarshall commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
>          // Wait at most 2 seconds for sub2's message to expire.
Same point about time difference here.

2021-04-24 04:51 UTC, michaeljmarshall commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
>          // Wait at most 2 seconds for sub3's message to expire.
Same point about time difference here.

2021-04-25 21:58 UTC, merlimat approved these changes

2021-04-25 21:58 UTC, merged