[pulsar-broker] Fix: handle failed partitions topic creation
apache/pulsar pull request #10374
Opened 2021-04-26 07:00 UTC by rdhabalia

### Motivation

Incrementing partition for the topic requires creating new partitions with existing subscriptions. Sometimes, partitions of the topic are distributed to multiple brokers, and the creation of few partitions may fail due to various reasons. However, retrying update-partition command for such topic fails with the below error
```
Caused by: org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Subscription already exists for topic
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:219) ~[classes/:?]
	at org.apache.pulsar.client.admin.internal.BaseResource$1.failed(BaseResource.java:129) ~[classes/:?]
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:839) ~[jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:820) ~[jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229) ~[jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62) ~[jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173) ~[jersey-client-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173) ~[jersey-client-2.31.jar:?]
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$0(AsyncHttpConnector.java:212) ~[classes/:?]

```

We frequently face this issue and need to manually update znode to fix the issue and increment partitions of the topic. 

### Modification
Handle `Subscription already exists for topic` error and create failed partitions to successfully increment partitions. Provide `force` flag to handle the error and successfully create partially created partitons.

2021-05-12 16:29 UTC, rdhabalia commented
/pulsarbot run-failure-checks

2021-06-01 02:58 UTC, codelipenghui approved these changes

2021-06-01 09:31 UTC, eolivelli requested changes
overall LGTM
but we are breaking the Admin API.

we should  not remove an existing method, but only add a new one

2021-06-01 09:31 UTC, eolivelli commented on pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
> +    void updatePartitionedTopic(String topic, int numPartitions, boolean updateLocalTopicOnly, boolean force)
it looks like we are dropping an API method.

we should keep the existing method, and add a new one that falls back to the new method, with force=false

2021-09-29 07:53 UTC, eolivelli approved these changes
LGTM

2021-10-06 21:17 UTC, merged