[log] Add line number to the log to make it easier to locate the prob…
apache/pulsar pull request #10463
Opened 2021-05-01 09:28 UTC by yangl

### Motivation

No line number is recorded in the current log file with the pattern `%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n`, which is not conducive to locating the problem.

### Modifications

update the log4j2 pattern, %d{HH:mm:ss.SSS} [%t] %-5level %logger{36}**#%L** - %msg%n

2021-05-01 13:42 UTC, lhotari commented
My assumption is that this has terrible performance implications since a stack trace is created internally for each log entry, no?

2021-05-01 18:45 UTC, merlimat approved these changes

2021-05-01 18:48 UTC, merlimat commented
> My assumption is that this has terrible performance implications since a stack trace is created internally for each log entry, no?

Oh, that might be true. I actually completely forgot why we didn't have the line number, but that could have been the reason.

2021-05-01 18:50 UTC, merlimat commented
Indeed, the impact is huge: https://logging.apache.org/log4j/2.x/performance.html#asyncLoggingWithLocation

2021-06-03 14:16 UTC, hangc0276 requested changes
The performance impaction is huge, we'd better locate bugs according to timestamp.

2021-06-03 15:22 UTC, lhotari commented
Closing this PR since the performance impact is too much.

2021-06-03 15:22 UTC, closed without merging