[Functions] Adding “numListenerThreads” configuration parameter in WorkerConfig . #8575
apache/pulsar pull request #10491
Opened 2021-05-06 09:28 UTC by xche

Fixes #8575

Motivation

The reason for this problem is that there is only one PulsarClient in a functionWorker instance, and the number of externalExecutorProvider thread pools in PulsarClient is 1, so all consumers share the same listener executor. Therefore, when one or more tasks stoped, the listener executor will be blocked, and finally other tasks will stop consuming data.

### Modifications

1. The same subscriber uses the same thread pool
2. Adding “numListenerThreads” configuration parameter in WorkerConfig
3. When PulsarSource is closed then clear queue to prevent listener executor from being blocked

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2021-05-06 10:01 UTC, xche commented
/pulsarbot run-failure-checks

2021-05-07 04:41 UTC, jerrypeng commented on pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactory.java
> +                rootClassLoader, exposePulsarAdminClientEnabled, pulsarWebServiceUrl, Optional.empty(),1);
Why are we setting the number of listener threads here to be one?  I think this config should also be respected with using the other runtimes as well.

2021-05-07 04:42 UTC, jerrypeng commented on pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PushPulsarSource.java
> +    public void clear() {
This code change doesn't seem relevant to this PR

2021-05-07 04:43 UTC, jerrypeng commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
> +        this.pinnedExecutor = (ScheduledExecutorService) executorProvider.getExecutor(conf.getSubscriptionName());
This code change doesn't seem relevant to this PR

2021-05-07 04:43 UTC, jerrypeng requested changes
There seems to be some changes that doesn't seem relevant to this PR

2021-05-08 13:04 UTC, freeznet submitted a review, later dismissed

2021-05-11 21:52 UTC, jerrypeng commented on pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactory.java
> +                rootClassLoader, exposePulsarAdminClientEnabled, pulsarWebServiceUrl, Optional.empty(),1);
This is not resolved

2021-05-12 09:29 UTC, xche commented
> @xche you added a config at the worker level but you PR only applies it to the ThreadRuntime and NOT the rest of the runtimes available.

2021-05-15 10:38 UTC, sijie commented
@jerrypeng Can you review this again?

2021-05-17 19:08 UTC, jerrypeng submitted a review, later dismissed

2021-05-26 08:22 UTC, codelipenghui commented
@xche Could you please help check the failed tests?

2021-06-11 06:23 UTC, xche commented
> @xche Could you please help check the failed tests?

@codelipenghui  The  failed tests related to this submission has been processed.  Could you please review this PR again?

2021-06-18 06:20 UTC, sijie approved these changes

2021-06-18 06:20 UTC, sijie commented
@xche Can you rebase to the latest master?

2021-06-18 08:37 UTC, xche commented
> @xche Can you rebase to the latest master?

@sijie rebase done

2022-01-18 01:57 UTC, codelipenghui commented
@xche Sorry for the late response, we have fixed a couple of flaky tests in the master branch, could you please try to rebased to the master branch and resolve the conflicts? It's better to have this one in 2.10.

2022-12-10 07:11 UTC, tisonkun commented
Rebased. @codelipenghui you may give another round.

Since we have 3 approvals already (dismissed now though), I'm going to merge this patch if CI passed and no more objection.

2022-12-10 07:14 UTC, tisonkun approved these changes

2022-12-10 10:08 UTC, tisonkun commented
It seems that since the codebase evolves a lot, function-related tests failed on this patch.

Close as stale. Please rebase and resubmit the patch if it's still relevant.

2022-12-10 10:08 UTC, closed without merging