get durable subscription without handling startMessageRollbackDurationSec
apache/pulsar pull request #10520
Opened 2021-05-09 07:59 UTC by linlinnn

**Motivation**
handle startMessageRollbackDurationSec when get durable subscription

2021-05-09 12:56 UTC, eolivelli requested changes
Nice.

Can you please add a test case?

2021-05-10 02:08 UTC, gaoran10 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
> +            if (ex != null) {
If the reset cursor operation is failed, the subscription still could be generated successfully, it seems that the configuration startMessageRollbackDurationSec is invalid, this has no effect on the users, right?

Maybe we could print a simple error message in the warning log.

2021-05-10 07:51 UTC, linlinnn commented
> Can you please add a test case?
@eolivelli any suggestion about this, `MockManagedLedger` do nothing.

2021-05-10 14:36 UTC, linlinnn commented
@eolivelli I have added unit test, please review again, thanks

2021-05-11 06:47 UTC, linlinnn commented
/pulsarbot run-failure-checks

2021-05-11 07:07 UTC, linlinnn commented
/pulsarbot run-failure-checks

2021-05-11 15:08 UTC, eolivelli approved these changes

2021-05-12 04:56 UTC, 315157973 approved these changes

2021-05-12 07:16 UTC, merged