reorganize the context hierarchy for functions
apache/pulsar pull request #10631
Opened 2021-05-18 22:21 UTC by nlu90

### Motivation

Currently the context relationship for function, source and sink is not well defined. This prevents some common features to be added once for all and creates some confusion, code duplication in the current repo. As demonstrated in the following graph, this PR changes the hierarchy from left to right. By introducing a common base context, it help solving some issues we are seeing. The base context provides common access to pulsar cluster, state, metrics, and meta-data to make sure all components can reuse it.

![context hierarchy](https://user-images.githubusercontent.com/16407807/118730483-8ebf5200-b7ec-11eb-9220-d41261f148bb.png)

### Modifications

- Remove `ConnectorContext` interface.
- Introduce a `BaseContext` interface. 
- Update existing `Context`, `SourceContext`, `SinkContext` interface to extend the new common interface.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - **The public API:**

2021-06-04 21:44 UTC, jerrypeng commented on pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/Producer.java
> +     *  Flush all the messages buffered in the client Asynchronously.
nit. Asynchronously -> asynchronously

2021-06-04 21:54 UTC, jerrypeng commented on pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java
> +@InterfaceStability.Unstable
why are changing the InterfaceStability level?  Is this change no backwards compatible?

2021-06-04 22:04 UTC, jerrypeng requested changes
While I am ok with doing some refactoring in the interfaces we have for Source, Sink, and Function context, this PR also exposes interfaces that are originally only for FunctionContext to SourceContext and SinkContext.  We should consider carefully before introducing these new interfaces in Source and Sink Context.  I don't want to expose functionality that is not needed.

If this is just a refactor, please keep the current interfaces exposed for FunctionContext, SourceContext, and SinkContext.

2021-06-07 20:00 UTC, nlu90 commented
> While I am ok with doing some refactoring in the interfaces we have for Source, Sink, and Function context, this PR also exposes interfaces that are originally only for FunctionContext to SourceContext and SinkContext. We should consider carefully before introducing these new interfaces in Source and Sink Context. I don't want to expose functionality that is not needed.
> 
> If this is just a refactor, please keep the current interfaces exposed for FunctionContext, SourceContext, and SinkContext.

@jerrypeng Thanks for the review.  Despite the previous shared interfaces, the followings new interfaces are exposed to connectors:

```
default <S extends StateStore> S getStateStore(String name) {
        throw new UnsupportedOperationException("Component cannot get state store");
    }

default PulsarAdmin getPulsarAdmin() {
        throw new UnsupportedOperationException("Component cannot access pulsar admin");
    }
    
default PulsarAdmin getPulsarAdmin(String clusterName) {
        throw new UnsupportedOperationException("Component cannot access pulsar admin");
    }

default <O> CompletableFuture<Void> publish(String topicName, O object, String schemaOrSerdeClassName) {
        throw new UnsupportedOperationException("Component cannot publish message");
    }

default <O> CompletableFuture<Void> publish(String topicName, O object) {
        throw new UnsupportedOperationException("Component cannot publish message");
    }

default <O> TypedMessageBuilder<O> newOutputMessage(String clusterName, String topicName, Schema<O> schema)
            throws PulsarClientException {
        throw new UnsupportedOperationException("Component can not output message to pulsar cluster");
    }
    
default <O> TypedMessageBuilder<O> newOutputMessage(String topicName, Schema<O> schema)
            throws PulsarClientException {
        throw new UnsupportedOperationException("Component can not output message to pulsar cluster");
    }

default <O> ConsumerBuilder<O> newConsumerBuilder(Schema<O> schema) throws PulsarClientException {
        throw new UnsupportedOperationException("Component can not create consumer builder");
    }
```

Based on my understanding, these are pulsar cluster interaction methods that connectors may need. And actually, I'm planning to add one more interface `getPulsarClient` as a following PR to fix https://github.com/apache/pulsar/pull/8668 more concretely. 

But I might be missing some of the context here, so please let me know which of the newly exposed functionality is not needed and we can discuss and update accordingly.

2021-06-09 22:50 UTC, jerrypeng commented
@nlu90 

> Based on my understanding, these are pulsar cluster interaction methods that connectors may need. And actually, I'm planning to add one more interface getPulsarClient as a following PR to fix #8668 more concretely.

1. I think the goal and scope of this PR is  refactor some of the code for various context interfaces so there is less duplicated code. Let's make the changes that are within that scope.   Let's not try to do too many things in one PR.

2. If we want to expose more of the interfaces of sources and sinks.  Let's have a clear use case in mind before exposing additional interfaces.  I am not in favor of just bulk adding additional interfaces for sources and sinks.  I don't want to maintain functionality in sources and sinks that is not useful.  For example, for a sink, is there a concrete use case in which a sink needs to publish a message to another pulsar topic?

2021-06-10 03:56 UTC, nlu90 commented
> @nlu90
> 
> > Based on my understanding, these are pulsar cluster interaction methods that connectors may need. And actually, I'm planning to add one more interface getPulsarClient as a following PR to fix #8668 more concretely.
> 
> 1. I think the goal and scope of this PR is  refactor some of the code for various context interfaces so there is less duplicated code. Let's make the changes that are within that scope.   Let's not try to do too many things in one PR.
> 2. If we want to expose more of the interfaces of sources and sinks.  Let's have a clear use case in mind before exposing additional interfaces.  I am not in favor of just bulk adding additional interfaces for sources and sinks.  I don't want to maintain functionality in sources and sinks that is not useful.  For example, for a sink, is there a concrete use case in which a sink needs to publish a message to another pulsar topic?

Sounds good to me.

I'll limit the scope of this PR for only refactoring apis. Keep those listed apis only in the FunctionContext. And send additional PRs if apis are needed.

2021-06-10 06:33 UTC, eolivelli reviewed
I share @jerrypeng concerns.
Apart from that I appreciate this work.

The fact that we are not changing the tests is a good demonstration that this is a compatible change from the API point of view

2021-06-18 06:19 UTC, sijie commented
@nlu90 Can you rebase the PR to the latest master?

2021-06-21 21:32 UTC, nlu90 commented
@sijie I rebased the master.

2021-06-22 22:38 UTC, nlu90 commented
@jerrypeng @eolivelli

Could you take another look at the PR?  I've updated it based on the comments and passed all the CI check

2021-06-22 22:40 UTC, jerrypeng approved these changes

2021-06-22 23:38 UTC, sijie approved these changes

2021-06-23 00:47 UTC, freeznet approved these changes

2021-06-23 19:58 UTC, merged