[Transaction] Transaction admin api get transaction status
apache/pulsar pull request #10690
Opened 2021-05-24 14:59 UTC by congbobo184

## Motivation
Transaction add admin api `getTransactionStatus`
## implement
```
@Data
public class TransactionStatus {

    /** The txnId of this transaction. */
    public String txnId;

    /** The status of this transaction. */
    public String status;

    /** The open time of this transaction. */
    public long openTimestamp;

    /** The timeout of this transaction. */
    public long timeoutAt;

    /** The producedPartitions of this transaction. */
    public Map<String, TransactionInBufferStats> producedPartitions;

    /** The ackedPartitions of this transaction. */
    public Map<String, Map<String, TransactionInPendingAckStats>> ackedPartitions;
}
```
### Verifying this change
Add the tests for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (yes)
Anything that affects deployment: (no)

2021-05-24 15:40 UTC, codelipenghui requested changes

2021-05-24 15:40 UTC, codelipenghui commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java
> +                TxnID txnID = txnMeta.id();
Will introduce NPE here.

2021-05-24 15:40 UTC, codelipenghui commented on pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTransactions.java
> +        jcommander.addCommand("transaction-status", new GetTransactionStatus());
It's better to use `transaction-metadata` here since we are using a transaction ID to fetch all transaction metadata through this command.

2021-05-24 15:40 UTC, codelipenghui commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java
> +                return registerSubscriptionMap.compute(topic + "-" + subscription, (key, future) -> {
Seems not related to this PR?

2021-05-24 15:52 UTC, congbobo184 commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java
> +                return registerSubscriptionMap.compute(topic + "-" + subscription, (key, future) -> {
test will use

2021-05-25 07:18 UTC, codelipenghui approved these changes

2021-05-25 07:18 UTC, merged