Increase the rate of topic creation
apache/pulsar pull request #11148
Opened 2021-06-29 12:41 UTC by suiyuzeng

### Motivation
The count of topic created in 1 second is less than 200, when the topic count of the namespace is about 200,000.

### Modifications
The reason is that the time cost of topic exist checking is too long when the topic count is large. 
In org.apache.pulsar.broker.admin.AdminResource#checkTopicExistsAsync, all the topics would be checked one by one. As the count of topic grows, the time cost will become longer.
Can we use org.apache.pulsar.broker.namespace.NamespaceService#checkTopicExists to check if the topic is exits?

2021-06-29 12:56 UTC, codelipenghui requested changes
Nice catch! But I think this will break the current behavior. Currently, we do not allow the duplicate topic name with the persistent or non-persistent domain, with this change it will only check the persistent topic duplication.

I think we should add the non-persistent topic duplication check back.

2021-06-30 11:50 UTC, suiyuzeng commented
> Nice catch! But I think this will break the current behavior. Currently, we do not allow the duplicate topic name with the persistent or non-persistent domain, with this change it will only check the persistent topic duplication.
> 
> I think we should add the non-persistent topic duplication check back.

Got it. I will update later.

2021-07-19 11:29 UTC, suiyuzeng commented
@codelipenghui hi, can you please take a look?

2021-07-19 11:49 UTC, 315157973 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
> +                    CommandGetTopicsOfNamespace.Mode.NON_PERSISTENT)
We have multiLayerTopicsMap in BrokerService, we don't need to traverse all NON_PERSISTENT, and then traverse again to determine whether it exists.
We only need to traverse the bundles, and then directly map.contains can do it, usually the number of bundles is not too much

2021-07-19 13:03 UTC, eolivelli reviewed
very nice catch !
I am happy to see an improvement here

do we have specific test cases around this function ?

2021-07-20 02:38 UTC, suiyuzeng commented
@315157973 @eolivelli thanks，i will Optimize the code and add some test about this function.

2021-07-28 06:31 UTC, 315157973 commented
@suiyuzeng Hello, please go on

2021-08-03 13:24 UTC, suiyuzeng commented
> @suiyuzeng Hello, please go on

Sorry, a little busy recently~
Find another problem, such as the test case "testCreatePartitionedTopicHavingNonPartitionTopicWithPartitionSuffix".  Some non partition topic has the partition suffix. In this case, we can not use the cache to check anymore. There is some checking about this issue in the current code, to ensure that we can not create no no-parititon topic whit -partition-xxx suffix.  How about add a config? If a cluster has the no-partition whit the suffix, use the current way to check duplication. If no no-paritition topic whit the suffix, use the cache to check.

2021-08-05 08:01 UTC, hangc0276 commented
> > @suiyuzeng Hello, please go on
> 
> Sorry, a little busy recently~
> Find another problem, such as the test case "testCreatePartitionedTopicHavingNonPartitionTopicWithPartitionSuffix". Some non partition topic has the partition suffix. In this case, we can not use the cache to check anymore. There is some checking about this issue in the current code, to ensure that we can not create no no-parititon topic whit -partition-xxx suffix. How about add a config? If a cluster has the no-partition whit the suffix, use the current way to check duplication. If no no-paritition topic whit the suffix, use the cache to check.

@suiyuzeng  Nice catch!
1. I am cutting 2.8.1, would you have time to address @315157973 's comments? 
2. for the restriction for reserved key-words for topic name, such as -partition-xx suffix for non-partitioned topic name, we have started a discussion for this issue: https://lists.apache.org/list.html?dev@pulsar.apache.org

2021-08-06 11:11 UTC, hangc0276 commented
move to 2.8.2

2021-11-01 10:08 UTC, 315157973 commented
move to 2.8.3

2022-02-11 18:38 UTC, michaeljmarshall commented
Removing the `release/2.8.3` label as this change will target master and probably won't be cherry picked back to stable branches because it is an optimization.

2022-12-10 07:22 UTC, tisonkun commented
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

I believe this patch is worth continuing, but holding a stale patch doesn't work. If @suiyuzeng can rebase and resubmit the patch, I'm glad to follow the PR lifecycle. Otherwise, I may pick it up later. Close.

2022-12-10 07:22 UTC, closed without merging