Cherry pick #11487 and #11560 to branch-2.7
apache/pulsar pull request #11574
Opened 2021-08-05 14:39 UTC by Technoboy-

2021-08-05 21:18 UTC, eolivelli requested changes
Can you please write in the description, and possibly the title, a summary of the changes?

Otherwise it is tricky for people reading the release notes and the commit messages to understand the meaning of this patch.

2021-08-05 21:20 UTC, eolivelli commented
Why didn't you use 'git  cherrypick -x'?

If you do it that way there is a better link to the original commits.
If they do not apply cleanly please explain

2021-08-06 01:57 UTC, Technoboy- commented
> Can you please write in the description, and possibly the title, a summary of the changes?
> 
> Otherwise it is tricky for people reading the release notes and the commit messages to understand the meaning of this patch.

Sorry for this, I have changed the description.

2021-08-06 03:16 UTC, Technoboy- commented
> Why didn't you use 'git cherrypick -x'?
> 
> If you do it that way there is a better link to the original commits.
> If they do not apply cleanly please explain

For some of the methods are different with the master branch, using git cherrypick -x will be failed. So I have to move the changes one by one.

2021-08-06 03:17 UTC, codelipenghui commented
@eolivelli 

> Why didn't you use 'git cherrypick -x'?

There are too many conflicts with branch-2.7. we are not able to cherry-pick the change from the master branch, so push a PR to fix the branch-2.7 directly.

2021-08-06 09:02 UTC, codelipenghui approved these changes

2021-08-06 15:22 UTC, eolivelli approved these changes

2021-08-09 09:30 UTC, merged