[consumer] Add seek by index for consumer
apache/pulsar pull request #12032
Opened 2021-09-14 05:11 UTC by Jason918

### Motivation

Currently we can reset the read position of a cursor by message id or timestamp. Since we formerly introduced index in broker metadata since 2.9.0, reset cursor by index is very helpful in other protocol handler (KoP or RoP). 

### Modifications

Added seekByIndex in consumer api.
The implementation is similar to seeking by timestamp.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
  - PersistentMessageFinderByIndexTest.java is unit test for the core finder implementation in broker.
  - ConsumerSeekTest.java is the integration test for client implementation.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API: (yes?)  added optional field 'index' in CommandSeek
  - The schema: ( no ) 
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: ( no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] doc-required 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] no-need-doc 
  
  (Please explain why)
  
- [x] doc 
  
  (If this PR contains doc changes) 
User can refer to the java doc in file pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java

2021-09-14 06:34 UTC, Jason918 commented
/pulsarbot run-failure-checks

2021-09-14 08:08 UTC, Jason918 commented
/pulsarbot run-failure-checks

2021-09-14 10:29 UTC, Jason918 commented
/pulsarbot run-failure-checks

2021-09-22 15:41 UTC, MarvinCai commented
it looks like we try to bake some sort of support for other message protocol into the broker itself?
will this just open up the potential to add more patches to make supporting other message protocol easier, then how far are we willing to go?

2021-09-23 02:42 UTC, Jason918 commented
> it looks like we try to bake some sort of support for other message protocol into the broker itself?
> will this just open up the potential to add more patches to make supporting other message protocol easier, then how far are we willing to go?

Message protocol handler is one of the great features in pulsar.
IMHO, It's important and useful to make other message protocol implementation easier. It's great for the messaging ecosystem. So we should add more new features supporting other message protocol as long as it does not breaking the design philosophy of pulsar.

@codelipenghui @jiazhai  What do you think of this?

2021-09-28 05:01 UTC, BewareMyPower commented
@MarvinCai It's not a support for other protocol, it's an enhancement. Currently Pulsar support the seek operation based on timestamp or message id. However, it doesn't support seek operation based on message count. For example, users might want to seek to 10000 messages before. Currently they cannot achieve this goal.
Pulsar 2.8.0 introduced BrokerEntryMetadata (PIP-70) and the message index (similar to Kafka's offset), so it becomes possible to support seeking by index now.

2021-09-28 05:22 UTC, BewareMyPower commented on pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerSeekTest.java
> +    public void testConsumerSeekByIndex() throws Exception {
It's better to move the test to `SubscriptionSeekTest`. And I don't think validating `markDeletePosition` is a good way, you can take other tests in `SubscriptionSeekTest` as reference.

2021-09-28 05:28 UTC, BewareMyPower requested changes

2021-09-28 05:28 UTC, BewareMyPower commented on pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java
> +     */
We should define the behavior for corner cases. For example, if there're 10 messages in a topic, i.e. the offset range varies from 0 to 9. What will happen if the given index is -1 or 10?

There is another corner case. If the offset range is `[10, 20)`, the oldest messages (`[0, 10)`) have been deleted. What will happen if the given index is less than 10?

BTW, it's a change for public API. I think we need a PIP first. /cc @merlimat

2021-09-29 03:39 UTC, Jason918 commented
/pulsarbot run-failure-checks

2021-09-29 04:42 UTC, Jason918 commented
/pulsarbot run-failure-checks

2021-09-29 05:36 UTC, MarvinCai commented
But not all users will use Index or event BrokerEntryMetadata, while all messages have Timestamp and MessageID, that's a bit different in my opinion. Adding a method that rely on a property might not exist for all users is kind of weird.

2021-09-29 05:40 UTC, MarvinCai commented
But let's discuss it with the community.

2022-02-07 06:26 UTC, Jason918 commented
Closing this for now, as there are not enough votes.

2022-02-07 06:27 UTC, closed without merging