[DOCS] Update io-debug.md
apache/pulsar pull request #13001
Opened 2021-11-27 09:34 UTC by sijia-w

Fixes #12691 

### Modifications

Add tab to config content and modify path format.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [x] `doc` 
  
  (If this PR contains doc changes)

2021-11-29 02:16 UTC, Anonymitaet requested changes

2021-11-29 02:16 UTC, Anonymitaet commented on site2/docs/io-debug.md
> +--archive pulsar-io-mongo-{{pulsar:version}} \
```suggestion
--archive connectors/pulsar-io-mongo-{{pulsar:version}}.nar \
```

FYI: https://github.com/apache/pulsar/pull/12691/files#r745592765

2021-12-02 01:58 UTC, Shoothzj approved these changes

2021-12-02 09:00 UTC, Anonymitaet approved these changes

2021-12-02 09:00 UTC, merged