Make sure the client can get response when encounter producer busy exception.
apache/pulsar pull request #13245
Opened 2021-12-12 05:09 UTC by codelipenghui

When the producer with the same producer ID and same connection,
Of course, this usually doesn't happen. When cherry-picking #12846,
the test using the same producer ID https://github.com/apache/pulsar/pull/12846/files#diff-b73845cd7706e03b89122a21b3e60c36c95ce6a0c7dd4574f8eda3fc67dd02b1R867-R876
And after we apply the change https://github.com/apache/pulsar/pull/8685/files#diff-1e0e8195fb5ec5a6d79acbc7d859c025a9b711f94e6ab37c94439e99b3202e84R1161
Only one request can get a response when encountering exceptions.

The fix is to make sure the broker doesn't miss the response to the client,
we should make sure one request can get one response, otherwise the client
side might get blocked.

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

2021-12-12 06:05 UTC, codelipenghui commented
/pulsarbot run-failure-checks

2021-12-12 06:15 UTC, michaeljmarshall requested changes
I think that we should keep the current behavior. The only time that the `producerFuture` is completed early is when the client sends a `CloseProducer` command, and in that case, the client is explicitly telling the broker to stop tracking the prior request.

Note that one primary failure here is caused by client timeouts. The client tries to create the same producer multiple times (and closes it each time the producer creation times out), and then if the broker finally loads the topic, the futures will execute from the stack. The first one succeeds, and the rest fail because they all have the same name as the first producer.

I will be interested to see what other community members think here. Please feel free to dismiss my review if this PR is accepted.

Edit: a previous version of this comment assumed that this PR was solely for branch-2.7. After talking with @codelipenghui on slack, I realize my initial interpretation of the PR was wrong.

2021-12-12 06:24 UTC, michaeljmarshall commented
Note that when I ran the test for branch-2.7, `ServerCnxTest`, I saw the following stack trace:

```
[ERROR] Tests run: 43, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 25.786 s <<< FAILURE! - in org.apache.pulsar.broker.service.ServerCnxTest
[ERROR] testCreateProducerTimeoutThenCreateSameNamedProducerShouldFail(org.apache.pulsar.broker.service.ServerCnxTest)  Time elapsed: 0.025 s  <<< FAILURE!
java.lang.AssertionError: expected [4] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.service.ServerCnxTest.testCreateProducerTimeoutThenCreateSameNamedProducerShouldFail(ServerCnxTest.java:878)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This happens because in `branch-2.7`, we respond even if the producer's future was already created. The test I wrote does not expect a response for request 1, but the 2.7 broker is sending a response. Here is the failing line in branch-2.7:

https://github.com/apache/pulsar/blob/4f19b8622d5d0d17973399883e492b839fc30f0a/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java#L883

2021-12-28 11:27 UTC, codelipenghui commented
@merlimat @315157973 @hangc0276 Please help check this one.

2021-12-28 11:36 UTC, eolivelli submitted a review, later dismissed
Makes sense to me.

@michaeljmarshall ?

2021-12-31 05:19 UTC, 315157973 approved these changes
LGTM

2022-01-03 21:28 UTC, michaeljmarshall commented
> Makes sense to me.
> 
> @michaeljmarshall ?

@eolivelli - did you see my above comment https://github.com/apache/pulsar/pull/13245#pullrequestreview-829587801? I am opposed to this change because it makes the broker send a response to a client request that is known to be timed out. The broker knows this because the client completed the `producerFuture` by sending a `CloseProducer` command before the producer was created. The net effect of this change is that the client will log a meaningless error message for every timeout out producer.

In my opinion, the core contract in this `ServerCnx` file is that the code that completes the `producerFuture` must also determine whether to send a response to the client. This change removes that contract and technically introduces a chance for the broker to respond to the same client request multiple times.

2022-01-03 21:32 UTC, eolivelli requested changes
@michaeljmarshall I missed your comment sorry

2022-01-10 14:24 UTC, wolfstudy commented
Thanks @codelipenghui 
This problem is very much like a problem encountered by the Go SDK community recently, and all the phenomena seem to match the description in this pr.

Through tcpdump, it was found that Go SDK sent ProducerCommand to the broker every time it reconnected, but the broker did not reply any Response to the client side, which caused the Go SDK to fail to reconnect until the entire client service was restarted.

And the issue refer to: https://github.com/apache/pulsar-client-go/issues/697

2022-01-12 06:46 UTC, michaeljmarshall commented
@wolfstudy - note that a 2.7.2 broker has the behavior that @codelipenghui is proposing here.

2022-02-15 01:10 UTC, closed without merging