Align configurations defaults between default file and Java object (broker.conf, proxy.conf, websocket.conf)
apache/pulsar pull request #13272
Opened 2021-12-13 12:53 UTC by nicoloboschi

Based on #13268 
### Motivation

In the default configuration files `conf/broker.conf`, `conf/proxy.conf` and `conf/websocket.conf` some entries are set with a value which differs from the Java one.

So if you comment out or you remove that line in the configuration file, the behavior changes.

### Modifications

* Aligned some Java properties to the file's value. Likely the user will not comment out the config lines so the expected behavior is that the config file contains the default values.
* Added tests to avoid future regressions 

### Does this pull request potentially affect one of the following parts:

 - The default values of configurations: yes
 
### Documentation

- [x] `doc`

2021-12-13 17:57 UTC, nicoloboschi commented
@eolivelli @codelipenghui PTAL

2021-12-13 18:00 UTC, merlimat requested changes
This is changing a lot of defaults which must not be changed.

2021-12-13 18:00 UTC, merlimat commented on pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
> +    private int numWorkerThreadsForNonPersistentTopic = 8;
This is done to use the number of available core. We must not change it.

2021-12-13 18:52 UTC, nicoloboschi commented on pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
> +    private int brokerDeduplicationSnapshotFrequencyInSeconds = 10;
This is value set in the broker.conf so it is the value used by default. The goal of this patch is not providing better defaults but to keep consistency if a user remove a configuration line. It is expected the values in the broker.conf are the default ones and not an "improved configuration". Do you agree?

2021-12-14 00:32 UTC, merlimat commented on pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
> +    private int brokerDeduplicationSnapshotFrequencyInSeconds = 10;
We need to fix these, but we need to fix them with default that make sense.

2021-12-14 08:35 UTC, nicoloboschi commented
@merlimat I addressed your comments. I also added a table in the PR description to better understand the configuration changes

2021-12-15 00:24 UTC, merlimat approved these changes
👍

2021-12-15 00:25 UTC, merged