fix(docs): update links in isolation docs
apache/pulsar pull request #13295
Opened 2021-12-14 13:37 UTC by ericsyh

Signed-off-by: Eric Shen <ericshenyuhao@outlook.com>

### Motivation

The command links in [https://pulsar.apache.org/docs/en/administration-isolation/](https://pulsar.apache.org/docs/en/administration-isolation/) are using [https://pulsar.apache.org/tools/pulsar-admin/](https://pulsar.apache.org/tools/pulsar-admin/) which is not clear for users to get to the target command.

### Modifications

Update the links in [https://pulsar.apache.org/docs/en/administration-isolation/](https://pulsar.apache.org/docs/en/administration-isolation/) to target command docs.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [x] `doc` 
  
  (If this PR contains doc changes)

2021-12-15 01:49 UTC, Huanli-Meng reviewed
leave one comment. PTAL

2021-12-15 01:49 UTC, Huanli-Meng commented on site2/website-next/versioned_docs/version-2.7.2/administration-isolation.md
> +For more information about the command `pulsar-admin ns-isolation-policy set`, see [here](https://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-em-).
why add a 2.8.0 link in 2.7.2 release?

2021-12-15 01:50 UTC, ericsyh commented on site2/website-next/versioned_docs/version-2.7.2/administration-isolation.md
> +For more information about the command `pulsar-admin ns-isolation-policy set`, see [here](https://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-em-).
That's a mistake, i'll update it.

2021-12-15 02:19 UTC, Huanli-Meng approved these changes
LGTM

2021-12-15 02:47 UTC, Anonymitaet requested changes

2021-12-15 02:47 UTC, Anonymitaet commented on site2/docs/administration-isolation.md
> +For more information about the command `pulsar-admin ns-isolation-policy set`, see [here](https://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-em-).
@ericsyh thanks for your consideration.
However, please do not change these general links to specified links, or else we need to update them for each release, there might be hundreds of occurrences. So here, we use general links on purpose.

2021-12-15 04:47 UTC, ericsyh commented on site2/docs/administration-isolation.md
> +For more information about the command `pulsar-admin ns-isolation-policy set`, see [here](https://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-em-).
I see. But it is confusing to me that why we need to have docs for each patch version? In my understanding, patch version onlly including bug fix and performance improvements and new features are only included in major and minor verion. So, we just need to keep one version docs for each minor version which means all 2.8.x verions just use a unified docs 2.8.

2021-12-15 06:58 UTC, Anonymitaet commented on site2/docs/administration-isolation.md
> +For more information about the command `pulsar-admin ns-isolation-policy set`, see [here](https://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-em-).
Minor versions include code improvements which need to update docs as well
For example, 
- https://github.com/apache/pulsar/pull/12539 need to update docs for 2.8.2 and 2.9.1, which means no need to update doc versions before 2.8.1
- Another example is, let's say, after a minor version is released, three months later, there is a patch to that release and needs to update docs, we need to make specific doc changes to that release as well

2021-12-16 04:51 UTC, ericsyh commented on site2/docs/administration-isolation.md
> +For more information about the command `pulsar-admin ns-isolation-policy set`, see [here](https://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-em-).
emmmm, https://github.com/apache/pulsar/pull/12539 seems a function enhenment PR and actually i think it should be released in a new minor version like  2.10.0 rathar than patch version 2.8.2 and 2.9.1. 

I take a look at other open source projects, most of them just maintain the minor version docs:
* [Flink](https://nightlies.apache.org/flink/flink-docs-release-1.14/):  
   <img width="236" alt="截屏2021-12-16 下午12 43 06" src="https://user-images.githubusercontent.com/10498732/146309601-08147466-14c0-42e6-a4d9-7d59e54dc281.png">

* [Kafka](https://kafka.apache.org/documentation/#gettingStarted): 
 <img width="657" alt="截屏2021-12-16 下午12 43 15" src="https://user-images.githubusercontent.com/10498732/146309723-2b4406ca-9f23-4784-ba7a-c6a22d39d392.png">

* [K8s](https://kubernetes.io/): 
   <img width="219" alt="截屏2021-12-16 下午12 43 23" src="https://user-images.githubusercontent.com/10498732/146309818-23944b7d-b1c4-4ae2-98a0-b869531c2e89.png">

It's really a heavy burden to maintain the docs for each patch version.

2021-12-17 08:21 UTC, Anonymitaet commented on site2/docs/administration-isolation.md
> +For more information about the command `pulsar-admin ns-isolation-policy set`, see [here](https://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-em-).
1. The code changes https://github.com/apache/pulsar/pull/12539 go into major and minor versions, so doc changes go those versions as well
![image](https://user-images.githubusercontent.com/50226895/146511755-c17b832f-bbf4-4da5-8009-7dd3e000a033.png)

2. Yes, Pulsar maintains versioned docs as well. For each minor version, for example, 2.7.x, you never know whether there might be code (doc) changes after it is released, so we maintain all of them for completeness
![image](https://user-images.githubusercontent.com/50226895/146512723-b74e3c3f-6c83-4dcd-ad55-0763e8883b9b.png)

2021-12-17 11:10 UTC, closed without merging