[Authorization] Reduce authz of ns operation from superUser to tenantAdmin
apache/pulsar pull request #13393
Opened 2021-12-18 16:08 UTC by yuruguo

This PR is similar to [13157](https://github.com/apache/pulsar/pull/13157)
### Motivation
Currently, there are some namespace operations that only `superUser` can access,. In fact, `tenantAdmin` of this namespace should also be able to access.
The namespace operations involved includes:
- set-bookie-affinity-group
- get-bookie-affinity-group
- unload-namespace-bundle
- split-namespace-bundle

So far, all namespace operation permissions belonging to `superUser` have been reduced to `tenantAdmin` in [NamespacesBase](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java).

### Documentation  
- [x] `no-need-doc`

2021-12-18 16:10 UTC, yuruguo commented
@eolivelli @michaeljmarshall @codelipenghui @315157973 PTAL, thx!

2021-12-20 04:09 UTC, yuruguo commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
> -                throw new RestException(Status.NOT_FOUND, "bookie-affinity group does not exist");
It is similar to this [PR](https://github.com/apache/pulsar/pull/13237#issue-1077409702)

2021-12-20 04:42 UTC, yuruguo commented
/pulsarbot run-failure-checks

2021-12-20 05:04 UTC, yuruguo commented
/pulsarbot run-failure-checks

2021-12-20 06:08 UTC, yuruguo commented
/pulsarbot run-failure-checks

2021-12-20 06:56 UTC, codelipenghui approved these changes

2021-12-20 08:45 UTC, yuruguo commented
/pulsarbot run-failure-checks

2021-12-20 12:32 UTC, eolivelli approved these changes
+1

2021-12-22 09:06 UTC, massakam commented
Should we grant these privileges to tenant administrators? At least in our company, we don't want tenant administrators to perform these operations on their own...

2021-12-22 09:09 UTC, eolivelli requested changes
> Should we grant these privileges to tenant administrators? At least in our company, we don't want tenant administrators to perform these operations on their own...

My understanding is that we are not reducing the power of current users, but we are allowing tenant Admins to perform more operations.

so you are saying that you do not want tenant admin to admin tenant level operations ?

I believe that you are correct, these operations, like managing bookies are not something you want a tenant admin to be able to manage.
also unloading things
it is very dangerous 

thanks for pointing it out

I am changing my position to -1 on this patch

2021-12-22 09:27 UTC, massakam commented
> so you are saying that you do not want tenant admin to admin tenant level operations ?

Yes, I think these operations should only be possible by the administrators of the entire Pulsar instance, i.e. the superuser.

2021-12-22 10:26 UTC, yuruguo commented
@massakam @eolivelli Thanks for your reply and checking, I have reverted the modification about `authz` part, and only keep [`fix return value in method internalGetBookieAffinityGroup`](https://github.com/apache/pulsar/pull/13393#discussion_r772068978)  part, in addition, I have also changed the title

PTAL again, thx!

2021-12-22 11:33 UTC, yuruguo commented
/pulsarbot run-failure-checks

2021-12-22 14:00 UTC, eolivelli commented
@yuruguo 
can you please close this PR and open a new one ?
otherwise comments are mixed and it is hard to understand the PR in the future for people who will try to understand this work

2021-12-22 14:20 UTC, yuruguo commented
/pulsarbot run-failure-checks

> @yuruguo can you please close this PR and open a new one ? otherwise comments are mixed and it is hard to understand the PR in the future for people who will try to understand this work

Okay :)

2021-12-22 14:20 UTC, closed without merging