bundle metrics would overwrite loadbalance metrics
apache/pulsar pull request #13641
Opened 2022-01-06 05:37 UTC by gaozhangmin

### Motivation
#12366  added bundle metrics, But, If we enabled expose these metrics, It would overwrite previous load balancing metrics.

### Modifications

seperate bundle metrics and load balance metrics

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

2022-01-06 06:25 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-01-06 06:57 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-01-06 07:59 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-01-11 06:27 UTC, gaozhangmin commented
@hangc0276  PTAL at this.

2022-01-18 05:23 UTC, codelipenghui approved these changes

2022-01-19 05:27 UTC, michaeljmarshall requested changes
Great catch. The code looks good to me. Before we merge this, can you please update the documentation? The doc is located here: `site2/docs/reference-metrics.md`.

2022-01-19 06:06 UTC, gaozhangmin commented
> Great catch. The code looks good to me. Before we merge this, can you please update the documentation? The doc is located here: `site2/docs/reference-metrics.md`.

@michaeljmarshall  Done.

2022-01-19 06:08 UTC, michaeljmarshall approved these changes
@gaozhangmin - Thanks! LGTM

2022-01-19 08:12 UTC, 315157973 approved these changes

2022-01-19 14:31 UTC, merged

2022-01-20 08:23 UTC, Anonymitaet commented
@michaeljmarshall docs are done in https://github.com/apache/pulsar/pull/12825/files, so I label this PR w/ `doc-added` and remove `doc-required`.

2022-01-20 22:03 UTC, michaeljmarshall commented
@Anonymitaet - thank you. I forgot to switch labels once the docs were added.