[Broker] Fix call sync method in async rest api for internalTerminatePartitionedTopic
apache/pulsar pull request #13890
Opened 2022-01-21 13:06 UTC by liudezhi2098

### Motivation

Avoid call sync method in async rest API for PersistentTopicsBase#internalTerminatePartitionedTopic.

### Modifications

- *Use async instead of sync method.*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Need to update docs? 
  
- [x] `no-need-doc`

2022-01-21 13:11 UTC, mattisonchao approved these changes

2022-01-21 13:49 UTC, Jason918 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> +                    Throwable cause = e.getCause();
Can this exception be handled by the `exceptionally` outside?
Seems like duplicate code.

2022-01-22 01:30 UTC, gaozhangmin requested changes

2022-01-22 01:30 UTC, gaozhangmin commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> +        future.thenAccept(__ -> validateTopicOwnershipAsync(topicName, authoritative)
Maybe here, We should first check the partition num before validateTopicOwnershipAsync. if partitionMetadata.partitions == 0, There is no need to validateTopicOwnershipAsync

2022-01-22 04:30 UTC, liudezhi2098 commented
/pulsarbot run-failure-checks

2022-01-22 05:59 UTC, gaozhangmin approved these changes

2022-01-22 09:43 UTC, Jason918 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> +        future.thenAccept(__ -> validateTopicOperationAsync(topicName, TopicOperation.TERMINATE)
need to use `thenCompose` to make it make check take effect.

2022-01-22 09:45 UTC, Jason918 requested changes

2022-01-22 09:45 UTC, Jason918 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> +                        validateTopicOwnershipAsync(topicName, authoritative).thenAccept(unused -> {
1. exception of `validateTopicOwnershipAsync` seems not handled.
2. I think we don't need to add `validateTopicOwnershipAsync` here.

2022-01-24 08:46 UTC, Jason918 approved these changes

2022-01-24 15:10 UTC, merged