[Issue 13756][Broker]Optimize topic policy with HierarchyTopicPolicies about replicatorDis…
apache/pulsar pull request #14161
Opened 2022-02-08 03:45 UTC by AnonHxy

Master Issue: https://github.com/apache/pulsar/issues/13756

### Motivation

See issue: https://github.com/apache/pulsar/issues/13756

### Modifications

* Add field `replicatorDispatchRate`  in `org.apache.pulsar.common.policies.data.HierarchyTopicPolicies`
* Methods to update `replicatorDispatchRate`  in `org.apache.pulsar.broker.service.AbstractTopic`
* Other Modifications are concerning on `org.apache.pulsar.broker.service.persistent.DispatchRateLimiter`  where  `replicatorDispatchRate` are used

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation
  
- [x] `no-need-doc`

2022-02-08 06:11 UTC, Jason918 requested changes

2022-02-08 06:11 UTC, Jason918 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
> +                    this.dispatchRateLimiter.ifPresent(DispatchRateLimiter::updateDispatchRate);
This is unrelated to this PR.

2022-02-10 09:25 UTC, Jason918 approved these changes
LGTM.
Left some minor comments.

2022-02-10 09:25 UTC, Jason918 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
>      public void initializeDispatchRateLimiterIfNeeded(Optional<Policies> policies) {
This params is not needed.

2022-02-11 01:59 UTC, AnonHxy commented
@Jason918 PTAL

2022-02-11 02:06 UTC, Jason918 approved these changes

2022-02-15 04:04 UTC, Jason918 approved these changes

2022-02-15 06:06 UTC, AnonHxy commented
/pulsarbot run-failure-checks

2022-02-17 10:38 UTC, Jason918 commented
@codelipenghui @315157973  PTAL

2022-02-24 13:02 UTC, codelipenghui approved these changes

2022-02-24 13:03 UTC, codelipenghui commented
@AnonHxy Could you please help resolve the conflicts?

2022-02-24 13:45 UTC, AnonHxy commented
@codelipenghui Ok, I push the code again

2022-02-24 15:19 UTC, AnonHxy commented
/pulsarbot run-failure-checks

2022-02-25 02:10 UTC, AnonHxy commented
I have resolved the conflicts,  PTAL @codelipenghui

2022-02-28 01:46 UTC, merged