[ci] add more single-test retries to reduce waste of resources caused by flaky tests
apache/pulsar pull request #14194
Opened 2022-02-09 18:31 UTC by nicoloboschi

### Motivation

In the unit tests github checks if a single test fails, then the whole job is rerun for at most 3 times. (using the [retry](https://github.com/apache/pulsar/blob/master/build/retry.sh) script).

Additionally, if a single test fails, there's [one attempt to rerun the test](https://github.com/apache/pulsar/blob/52b7059bdac7120f319a3c6f8085f25a2b9de7c8/buildtools/src/main/java/org/apache/pulsar/tests/RetryAnalyzer.java#L27). This parameter is configurable. The default (and actual value) is 1.

We can retry to run the single failing test before giving up and rerun the whole suite.
The benefits are multiple:
* Fast PR validations
* More stable PR validations (less need to re-trigger the CI)
* Less waste of resources in case the test passes on the second or third shot 

### Modifications
- Set `testRetryCount` to 6 on the unit test suites
  
### Documentation

- [x] `no-need-doc`

2022-02-09 20:06 UTC, dlg99 approved these changes

2022-02-09 20:10 UTC, lhotari requested changes
-1. I don't think that making flakes pass silently is a good idea. For more context, please check the document [[Discuss] PIP Changes to flaky test handling](https://docs.google.com/document/d/10lmn4pW1IsT_8D1ZE0vMjASX0HhjdGdjB794iyScwns/edit) .

> A critical problem of the current test retry solution is that it can mask bugs in production code and make the build pass and allow changes to be merged that cause regressions. There isn't a straight-forward way to detect whether the flakiness in a test is a result of a bad test or an actual bug in production code.

2022-02-09 20:25 UTC, nicoloboschi commented
@lhotari I see your points and it makes sense to me. However I still think that re-running the whole suite in case of single-test failure is not a good idea. I changed the PR according to this.

2022-02-10 01:04 UTC, mattisonchao commented
> -1. I don't think that making flakes pass silently is a good idea. For more context, please check the document [[Discuss] PIP Changes to flaky test handling](https://docs.google.com/document/d/10lmn4pW1IsT_8D1ZE0vMjASX0HhjdGdjB794iyScwns/edit) .
> 
> > A critical problem of the current test retry solution is that it can mask bugs in production code and make the build pass and allow changes to be merged that cause regressions. There isn't a straight-forward way to detect whether the flakiness in a test is a result of a bad test or an actual bug in production code.

Agree with @lhotari,  Many flaky tests are actually production code issues so we need to track and resolve them.

2022-02-10 14:07 UTC, closed without merging