[Broker] fix error log miss stack trace when create tenant fail
apache/pulsar pull request #14366
Opened 2022-02-18 05:53 UTC by wangjialing218

### Motivation

When create tenant fail, the error log did not print out the stack trace.

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### Documentation
- [x] `no-need-doc` 
only a fix for error log

2022-02-18 06:10 UTC, Shoothzj approved these changes

2022-02-18 07:33 UTC, Technoboy- approved these changes

2022-02-18 07:37 UTC, wangjialing218 commented
/pulsarbot rerun-failure-checks

2022-02-19 04:53 UTC, mattisonchao requested changes

2022-02-19 04:53 UTC, mattisonchao commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
>                      asyncResponse.resume(new RestException(ex));
Maybe we need to unwrap the exception?

2022-02-19 04:53 UTC, mattisonchao commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
>                  asyncResponse.resume(new RestException(ex));
Maybe we need to unwrap the exception?

2022-02-19 04:55 UTC, mattisonchao approved these changes

2022-02-20 00:53 UTC, Jason918 approved these changes

2022-02-21 01:55 UTC, wangjialing218 commented
/pulsarbot run-failure-checks

2022-02-21 06:25 UTC, wangjialing218 commented
/pulsarbot run-failure-checks

2022-02-21 11:19 UTC, liudezhi2098 approved these changes

2022-02-21 14:23 UTC, merged