[fix][package-management] Fix the new path `/data` introduced regression
apache/pulsar pull request #15367
Opened 2022-04-28 08:57 UTC by zymap

---

Fixes #15362

*Motivation*

The PR https://github.com/apache/pulsar/pull/13218 supports saving
package data into filesystem. But it introduces a regression for the
old versions.
For example, we have a package function://public/default/package@v0.1,
it will save the meta to the path function/public/default/package/v0.1/meta,
and save the data to the path function/public/default/package/v0.1.
By default, we are using distributed log as the package storage, and
it supports saving data in a directory.
But some storage like filesystem doesn't have the similar ability, it
needs another path for saving data.
This API provides the ability to support saving the data in another place.
If you specify the data path as `/data`, the package will be saved into
function/public/default/package/v0.1/data.

*Modifications*

- make the data path configurable in the storage implementation.

2022-04-28 08:59 UTC, zymap commented
We have tests for the package service both bk storage and filesystem storage. It's a compatibility issue so I think it's hard to add a test for that.

2022-04-28 09:00 UTC, zymap commented
@nlu90 @eolivelli PTAL

2022-04-28 19:36 UTC, nlu90 approved these changes

2022-04-29 03:00 UTC, zymap commented
ping @merlimat @eolivelli

2022-04-29 03:56 UTC, hangc0276 approved these changes

2022-04-29 08:32 UTC, nicoloboschi requested changes
Good work!

>We have tests for the package service both bk storage and filesystem storage. It's a compatibility issue so I think it's hard to add a test for that.

I believe that a unit test that ensures the default value (for different storage implementations) it would be very useful as we would have been able to spot the regression during the development of https://github.com/apache/pulsar/pull/13218

2022-04-30 04:04 UTC, freeznet approved these changes

2022-05-02 14:52 UTC, HQebupt approved these changes

2022-05-05 01:51 UTC, murong00 approved these changes

2022-05-05 07:01 UTC, zymap commented
@nicoloboschi PTAL. Thanks

2022-05-05 08:07 UTC, nicoloboschi approved these changes
thanks for adding the test
LGTM

2022-05-06 02:04 UTC, merged