PIP-155: Removed Python 2 support
apache/pulsar pull request #15376
Opened 2022-04-28 23:31 UTC by merlimat

### Motivation

 * Remove Python 2 from build scripts

### Modifications

 * Use Python3 in build image
 * Update build image to ubuntu:20.04 (There is no Python 3.7 support in the old Ubuntu)
 * Use `python3` instead of `python` in the executable scripts

2022-04-29 05:54 UTC, BewareMyPower commented
```
CMake Error at CMakeLists.txt:272 (string):
  string sub-command REPLACE requires at least four arguments.


-- PYTHON: 
```

It looks like `find_package(PythonLibs REQUIRED)` didn't find the `PYTHONLIBS_VERSION_STRING` correctly.

2022-05-05 01:54 UTC, hangc0276 approved these changes

2022-05-05 02:26 UTC, BewareMyPower requested changes
It looks like now we use higher `clang-format` to format C++ source code. Could you update it in pulsar-client-cpp/README.md? See https://github.com/apache/pulsar/tree/master/pulsar-client-cpp#requirements-for-contributors.

Because the rule of latest `clang-format` is a little different with `clang-format-5.0`.

2022-05-05 03:19 UTC, BewareMyPower approved these changes

2022-05-05 06:01 UTC, merged