Use unique consumer name when create sub
apache/pulsar pull request #15468
Opened 2022-05-06 08:59 UTC by wolfstudy

Signed-off-by: xiaolongran <xiaolongran@tencent.com>

### Motivation

Currently, if the user does not specify the producerName when creating the producer, the broker will generate a unique ProducerName field:

```
        // Use producer name provided by client if present
        final String producerName = cmdProducer.hasProducerName() ? cmdProducer.getProducerName()
                : service.generateUniqueProducerName();
```

However, when the sub is created and the user does not specify a consumerName, an empty string is used instead:

```
final String consumerName = subscribe.hasConsumerName() ? subscribe.getConsumerName() : "";
```

Under normal circumstances, this seems to be no problem, but when many topics reuse the same client, and for some reason, the connection is frequently disconnected, reconnected, disconnected, and reconnected. In this way, we can see that there are many consumer objects with the same consumerName under the current subscription through `bin/pulsar-admin topics stats <topic-name>`.

The following is a phenomenon we encountered in the production environment. This `consumerName: exchange-wal-consumer-9.1x.1x.x-3953a` has a total of **997** consumer objects with the same name under this topic.

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/20965307/167100529-f1d88a11-77ba-48c4-81d4-96d2f5b36e88.png">

### Modifications

- Use unique consumer name when create sub

2022-05-06 13:29 UTC, poorbarcode commented
Hi @wolfstudy  

It seems rude to do so. It breaks the subscribe rate limit policy.

https://github.com/apache/pulsar/blob/c35ac3f765fd20e22ce9869f1f71fa3d5fa96149/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java#L41

https://github.com/apache/pulsar/blob/c35ac3f765fd20e22ce9869f1f71fa3d5fa96149/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java#L252-L260

2022-05-06 13:50 UTC, wolfstudy commented
> consumerName

Why break the subscribe rate limit policy?

2022-05-06 13:51 UTC, wolfstudy commented
> Hi @wolfstudy
> 
> It seems rude to do so. It breaks the subscribe rate limit policy.
> 
> https://github.com/apache/pulsar/blob/c35ac3f765fd20e22ce9869f1f71fa3d5fa96149/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java#L41
> 
> https://github.com/apache/pulsar/blob/c35ac3f765fd20e22ce9869f1f71fa3d5fa96149/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java#L252-L260

Why break the subscribe rate limit policy?

2022-05-06 14:31 UTC, poorbarcode commented
> Why break the subscribe rate limit policy?

In original design: the consumer returned by `pulsarClient.newConsumer(Schema.BYTES).topic("my-topic").subscriptionName("my-subscription").subscribe()`  no matter how many times you subscribe, will use same `subscribe-RateLimiter`.  This patch has broken this design.

2022-05-06 14:40 UTC, poorbarcode commented
> Why break the subscribe rate limit policy?

Maybe rewrite `ConsumerIdentifier.equals()` can solve the problem, but be compatible if the user has already set the consumer-name.

I don't mean to offend you, I'm just making a point.  I also think it's not perfect that consumers don't have names.

2022-06-06 07:06 UTC, eolivelli requested changes
I am not sure about the value of this patch.
if the client sets a consumerName, then you will have the same "problem" anyway.

if your problem is about the Consumer that cannot work properly in case of frequent reconnections, then we have to fix the problem somewhere else, this patch is only a workaround.

2022-12-10 14:42 UTC, tisonkun commented
Closed as stale and no consensus. Please rebase and resubmit the patch if it's still relevant.

2022-12-10 14:42 UTC, closed without merging