[fix][txn]Fix transasction ack batch message
apache/pulsar pull request #15875
Opened 2022-06-01 08:29 UTC by liangyepianzhou

Fixes https://github.com/apache/pulsar/issues/15832

### Motivation
Transaction needs batch size to help determine whether the batch message is in the pending ack state.

### Modifications
Returns the batch size of messageID directly.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

2022-06-02 09:17 UTC, congbobo184 approved these changes

2022-06-02 09:24 UTC, congbobo184 requested changes

2022-06-02 09:24 UTC, congbobo184 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
> +            long batchSize = msgId.getBatchSize();
don't change this method; if this message is not a batch message, the batchSize will set it to -1. Batch size is used to change unAckMessageCount, is it should be 1, not -1, and not 0. so I only suggest change positionsAcked not this batchSize

2022-06-06 11:19 UTC, liangyepianzhou commented
/pulsarbot run-failure-checks

2022-06-07 02:28 UTC, Jason918 approved these changes
LGTM

2022-06-07 04:43 UTC, congbobo184 approved these changes

2022-06-07 04:45 UTC, merged