Async subscription dispatch rate
apache/pulsar pull request #15880
Opened 2022-06-01 13:46 UTC by gaoyanliang

### Motivation

See PIP https://github.com/apache/pulsar/issues/14365 and change tracker https://github.com/apache/pulsar/issues/15043.

MakesetSubscriptionDispatchRate / getSubscriptionDispatchRate / deleteSubscriptionDispatchRate methods to pure async.

### Documentation

- [x] `no-need-doc`

2022-06-01 13:48 UTC, gaoyanliang commented
@shibd @Technoboy- @mattisonchao  PTAL

2022-06-01 13:51 UTC, gaoyanliang commented
Hi @Technoboy- Can you help trigger the ci ？

2022-06-01 16:11 UTC, shibd commented
@gaoyanliang CI should be able to trigger automatically because you are not submitting pr for the first time.

When the ci job failed, you can use cmd`/pulsarbot run-failure-checks` to rerun these jobs(write in the comment area).

2022-06-02 01:08 UTC, gaoyanliang commented
> @gaoyanliang CI should be able to trigger automatically because you are not submitting pr for the first time.
> 
> When the ci job failed, you can use cmd`/pulsarbot run-failure-checks` to rerun these jobs(write in the comment area).

ok, get it. Thanks

2022-06-02 01:15 UTC, shibd approved these changes
/LGTM

2022-06-02 01:15 UTC, shibd commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
> +                                        @PathParam("namespace") String namespace) {
invalid change

2022-06-02 01:21 UTC, Technoboy- commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
> +                    log.error("Failed to set the subscription dispatchRate for cluster on namespace {}",
We add clientAppId in the log like :l
log.error("[{}] Failed to set the subscription dispatchRate for cluster on namespace {}", clientAppId(), namespaceName, ex);

2022-06-02 01:21 UTC, Technoboy- commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
> +                            , namespaceName, ex);
and here

2022-06-02 01:21 UTC, Technoboy- commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
> +                            , namespaceName, ex);
and here

2022-06-02 03:22 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-06 01:14 UTC, gaoyanliang commented
@Technoboy-  @mattisonchao  ptal.

2022-06-06 09:48 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-06 10:31 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-06 11:14 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-07 01:55 UTC, gaoyanliang commented
@Technoboy-  @mattisonchao  All checks have passed. PTAL

2022-06-09 09:47 UTC, gaoyanliang commented
@Technoboy- @mattisonchao  PTAL。

2022-06-13 01:24 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-13 03:44 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-13 03:51 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-14 02:22 UTC, Technoboy- approved these changes

2022-06-16 02:56 UTC, RobertIndie requested changes

2022-06-16 02:56 UTC, RobertIndie commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
>          validateNamespacePolicyOperation(namespaceName, PolicyName.RATE, PolicyOperation.READ);
Need to remove this line.

2022-06-16 03:35 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-16 03:45 UTC, Demogorgon314 approved these changes

2022-06-16 03:55 UTC, RobertIndie approved these changes

2022-06-16 04:49 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-16 05:57 UTC, gaoyanliang commented
/pulsarbot run-failure-checks

2022-06-16 08:25 UTC, mattisonchao approved these changes

2022-06-17 00:53 UTC, merged