[fix][client] Register logical type conversions when use `SchemaDefinition.<T>builder().withJsonDef()`
apache/pulsar pull request #15915
Opened 2022-06-03 03:15 UTC by coderzc

Fixes #15899

### Motivation

Now, don‘t register logical type conversions when use `SchemaDefinition.<T>builder().withJsonDef()`

### Modifications

Register logical type conversions when use `SchemaDefinition.<T>builder().withJsonDef()`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests and can be verified

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

2022-06-06 08:17 UTC, codelipenghui approved these changes

2022-06-06 10:01 UTC, shibd approved these changes
/LGTM

2022-06-06 11:10 UTC, coderzc commented
> PR

What means?
This PR modifies `SchemaUtil` rather than `StructSchema`.

2022-06-08 02:33 UTC, mattisonchao approved these changes

2022-06-09 03:53 UTC, codelipenghui commented
/pulsarbot run-failure-checks

2022-06-09 09:16 UTC, mattisonchao commented
/pulsarbot run-failure-checks

2022-06-09 09:38 UTC, mattisonchao commented
Hi @coderzc 

We re-run the test many times, but the test still fails. Could you take a look?

2022-06-09 12:11 UTC, coderzc commented
/pulsarbot run-failure-checks

2022-06-09 16:11 UTC, coderzc commented
/pulsarbot run-failure-checks

2022-06-10 16:16 UTC, coderzc commented
/pulsarbot run-failure-checks

2022-06-10 17:17 UTC, coderzc commented
/pulsarbot run-failure-checks

2022-06-12 12:07 UTC, codelipenghui requested changes

2022-06-12 12:07 UTC, codelipenghui commented on pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinitionBuilder.java
> +    SchemaDefinitionBuilder<T> withClassLoader(ClassLoader classLoader);
If need to add a public API to fix the issue, it should start with a proposal first.

2022-06-22 03:43 UTC, codelipenghui approved these changes

2022-06-23 07:54 UTC, coderzc commented
@congbobo184 @mattisonchao PTAL

2022-06-23 16:34 UTC, merged