[fix][admin]allowAutoTopicCreation and allowAutoTopicCreationType etc should be dynamically configured
apache/pulsar pull request #16023
Opened 2022-06-12 14:20 UTC by Radiancebobo

allowAutoTopicCreation and allowAutoTopicCreationType etc should be dynamically configured

Fixes #16020 

### Motivation
In the broker.conf configuration, there are these configurations:

- allowAutoTopicCreation
- allowAutoTopicCreationType
- brokerDeleteInactiveTopicsEnabled
- brokerDeleteInactiveTopicsFrequencySeconds
- brokerDeleteInactiveTopicsMaxInactiveDurationSeconds
- allowAutoSubscriptionCreation
I think these should be dynamically configurable.

Pulsar has namespace-level policy, but the broker-level dynamically  configuration is missing. 

### Modifications
The change is very simple, just add dynamic identification to these configurations in ServiceConfiguration.java, and add a callback function when updating.

### Documentation

Need to update docs? 

- [x] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-complete`
(Docs have been already added)

2022-06-12 14:33 UTC, codelipenghui reviewed
The change looks good. Could you please add a UT for the new change? 

Here is an example PR https://github.com/apache/pulsar/pull/13121 which added `subscriptionTypesEnabled` dynamic configuration support.

2022-06-13 04:19 UTC, Radiancebobo commented
> The change looks good. Could you please add a UT for the new change?
> 
> Here is an example PR #13121 which added `subscriptionTypesEnabled` dynamic configuration support.

OK, I will supplement the corresponding unit tests as soon as possible

2022-06-15 01:05 UTC, Radiancebobo commented
Unit tests that fail to run also happen on the master branch, it doesn't look like it's caused by my commits, I'll try my best to take the time to fix them.

2022-06-15 03:15 UTC, AnonHxy approved these changes

2022-06-15 09:08 UTC, Demogorgon314 reviewed
Overall LGTM, just left some small comments.

2022-06-23 01:17 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 02:26 UTC, Jason918 approved these changes
LGTM

2022-06-23 04:19 UTC, Radiancebobo commented
org.apache.pulsar.broker.admin.AdminApiTest ► testGetPartitionedStatsInternal：
![image](https://user-images.githubusercontent.com/39521534/175202898-21a7d783-84f3-4779-a574-8ef41f90c68f.png)
Successfully run multiple times in my local environment：
![image](https://user-images.githubusercontent.com/39521534/175202928-93164293-1c22-4ccc-b6c7-516b40701f00.png)


org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest ► testAddRemoveConsumer：
![image](https://user-images.githubusercontent.com/39521534/175203283-184bf7c8-ee1c-4d1a-aa12-7df73494efa6.png)
Successfully run multiple times in my local environment：
![image](https://user-images.githubusercontent.com/39521534/175203336-c62b61dc-bcb7-431d-bd9c-b8e22278cd47.png)


org.apache.pulsar.metadata.ZKSessionTest ► testSessionLost：
![image](https://user-images.githubusercontent.com/39521534/175203702-d36454d7-8124-4575-a6dd-0877e7446332.png)
Runs successfully many times in my local environment, but occasionally fails:
![image](https://user-images.githubusercontent.com/39521534/175204483-0bfcd10a-b3ec-46f5-9ffd-bc40d2a6226f.png)
![image](https://user-images.githubusercontent.com/39521534/175204641-ce1be4ea-35c9-4a87-a5bc-662736457236.png)

2022-06-23 04:47 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 06:11 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 06:59 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 07:19 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 07:24 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 08:36 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 08:47 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 11:27 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-23 14:27 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-29 01:30 UTC, Demogorgon314 commented
@codelipenghui @BewareMyPower Please help review this PR. The required test has already passed.

2022-06-29 09:37 UTC, BewareMyPower commented
Please rebase to master to resolve conflicts.

2022-06-30 10:07 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-06-30 14:54 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-07-01 03:27 UTC, BewareMyPower requested changes

2022-07-01 03:27 UTC, BewareMyPower commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java
> +    }
Don't use `Thread.sleep`, use `Awaitility.await().atMost(/* ... */)`.

I noticed some existing tests might also use `Thread.sleep`, but it's not good. For new tests, it's better not to sleep.

2022-07-01 03:41 UTC, BewareMyPower commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoSubscriptionCreationTest.java
> +        }
We can simplify this type of verification to

```java
        Assert.assertThrows(PulsarClientException.class, () ->
                pulsarClient.newConsumer().topic(topicString).subscriptionName(subscriptionName).subscribe());
```

I think we can also apply similar changes to `testDynamicConfigurationTopicAutoCreationDisable`.

2022-07-01 07:12 UTC, BewareMyPower requested changes

2022-07-01 07:12 UTC, BewareMyPower commented on conf/client.conf
> +brokerServiceUrl=pulsar://localhost:6651,localhost:6652,localhost:6653/
Please revert unnecessary changes.

2022-07-01 07:15 UTC, BewareMyPower commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java
>          });
I mean, use `atMost` method to control the timeout explicitly. See https://www.javadoc.io/doc/org.awaitility/awaitility/3.0.0/org/awaitility/Awaitility.html

2022-07-01 07:54 UTC, Radiancebobo commented on conf/client.conf
> +brokerServiceUrl=pulsar://localhost:6651,localhost:6652,localhost:6653/
oh, sorry.

2022-07-01 08:46 UTC, BewareMyPower reviewed
Could you add `atMost` to other tests of `InactiveTopicDeleteTest` as well?

2022-07-01 09:27 UTC, Radiancebobo commented
> Could you add `atMost` to other tests of `InactiveTopicDeleteTest` as well?

ok

2022-07-01 11:14 UTC, BewareMyPower approved these changes

2022-07-02 00:32 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-07-02 05:11 UTC, Radiancebobo commented
/pulsarbot run-failure-checks

2022-07-02 05:36 UTC, Radiancebobo commented
@BewareMyPower  Can you help me merge this branch to master?

2022-07-04 01:24 UTC, merged