Fix miss flushing ack request when invoking pendingIndividualBatchInd…
apache/pulsar pull request #16033
Opened 2022-06-13 05:07 UTC by gaozhangmin

### Motivation
#15877 missed another condition  where `flush` should be invoked.

### Modifications

Flush ack request after `pendingIndividualBatchIndexAcks` size >= MAX_ACK_GROUP_SIZE when doing `addListAcknowledgment(messageIds)`

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

  
- [x] `doc-not-needed` 
(Please explain why)

2022-06-13 14:22 UTC, codelipenghui reviewed
It's better to add an UT for the new change to avoid regression.

2022-06-13 17:25 UTC, gaoran10 commented
Maybe we'd better add this inspection at where the `pendingIndividualBatchIndexAcks` changed, otherwise if there is a new method to call the method `doIndividualBatchAckAsync`, it also needs to add this inspection.

2022-06-14 07:03 UTC, lhotari requested changes
Please add tests that cover the issue.

2022-06-14 07:03 UTC, lhotari commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java
> -            }
This change doesn't match the PR description.

2022-06-15 08:34 UTC, gaozhangmin commented
When i was adding UT, i found there may exists another problem:  Message ack  in a batch will be added to `pendingIndividualBatchIndexAcks`,  After the BitSet all set to false(means all acked, but the ack requests are not sent yet),  a normal ack request  will be send to broker, and the batch index ack will be removed from `pendingIndividualBatchIndexAcks` before we send it to broker. @gaoran10 @lhotari @codelipenghui

2022-06-22 05:35 UTC, gaozhangmin commented
It's impossible that flush is trigger by `pendingIndividualBatchIndexAcks` size.  according to he above description.

2022-07-14 10:11 UTC, closed without merging