[security] Bump ES client version to 8.2.3
apache/pulsar pull request #16110
Opened 2022-06-17 11:21 UTC by tisonkun

### Motivation

This fixes CVE-2022-23712.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)

This fixes CVE-2022-23712.

  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

2022-06-17 11:41 UTC, nicoloboschi requested changes
The CVE is related to the Elastic server. we should add a suppression for the OWASP check

2022-06-17 13:23 UTC, tisonkun commented
@nicoloboschi Thanks! Will update it.

2022-06-17 14:36 UTC, tisonkun commented
cc @lhotari

2022-06-17 15:04 UTC, RobertIndie approved these changes

2022-06-17 15:23 UTC, nicoloboschi requested changes

2022-06-17 15:23 UTC, nicoloboschi commented on src/owasp-dependency-check-suppressions.xml
> +        <gav>org.elasticsearch.client:elasticsearch-rest-client:8.1.0</gav>
could you use the sha1 here?

2022-06-17 15:23 UTC, nicoloboschi commented on src/owasp-dependency-check-suppressions.xml
> +        <gav>co.elastic.clients:elasticsearch-java:8.1.0</gav>
could you use the sha1 here?

2022-06-18 03:23 UTC, tisonkun commented on src/owasp-dependency-check-suppressions.xml
> +        <gav>co.elastic.clients:elasticsearch-java:8.1.0</gav>
Hi @nicoloboschi what's the different between `gav` and `sha1`, or what's the benefit to use `sha1`? Also, how can I get the corresponding `sha1` of this artifact?

2022-06-19 04:45 UTC, tisonkun commented on src/owasp-dependency-check-suppressions.xml
> +        <gav>co.elastic.clients:elasticsearch-java:8.1.0</gav>
It seems that I can get the value of `sha1` from https://repo1.maven.org/maven2/co/elastic/clients/elasticsearch-java/8.1.0/elasticsearch-java-8.1.0.jar.sha1 and ditto rest-client.

I'll make an update but still wonder what's the benefit it brings.

2022-06-19 04:59 UTC, tisonkun commented
Now it report a new vulnerability. Shall I include the resolution in this PR?

```
Error:  Failed to execute goal org.owasp:dependency-check-maven:7.1.0:aggregate (default) on project pulsar: 
Error: 
Error:  One or more dependencies were identified with vulnerabilities that have a CVSS score greater than or equal to '7.0': 
Error: 
Error:  fastjson-1.2.73.jar: CVE-2022-25[8](https://github.com/apache/pulsar/runs/6952840802?check_suite_focus=true#step:8:9)45(9.8)
Error: 
Error:  See the dependency-check report for more details.
Error:  -> [Help 1]
Error: 
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error: 
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: 
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :pulsar
Error: Process completed with exit code 1.
```

2022-06-19 05:12 UTC, tisonkun commented
I pushed a commit to update fastjson for the latest patch version. Otherwise CI always failed :(

2022-06-19 09:40 UTC, tisonkun commented
Tests failed on CI - Build - MacOS / Unit-BROKER_FLAKY Tests. I think it's flaky test since #16109 passed.

2022-06-20 12:11 UTC, tisonkun commented
cc @nicoloboschi @lhotari

2022-06-20 12:25 UTC, nicoloboschi commented on src/owasp-dependency-check-suppressions.xml
> +        <gav>co.elastic.clients:elasticsearch-java:8.1.0</gav>
Actually I open the OWASP html report and click on the "add suppression" button to get the SHA-1.

2022-06-20 12:26 UTC, nicoloboschi commented
@tisonkun we have to do the upgrade of fastjson in another pull. WIll merge this one even if the OWASP will fail but it's better to have two different pulls (easier to revert, to cherry-pick)

2022-06-20 12:46 UTC, tisonkun commented
@nicoloboschi thanks for your explanation. Will push a commit to revert fastjson changes and do it in another PR.

2022-06-20 12:47 UTC, tisonkun commented
Updated.

2022-06-20 12:48 UTC, tisonkun commented on src/owasp-dependency-check-suppressions.xml
> +        <gav>co.elastic.clients:elasticsearch-java:8.1.0</gav>
Thanks for your information! I've addressed this comment.

2022-06-21 05:20 UTC, nicoloboschi approved these changes

2022-06-21 05:21 UTC, merged

2022-06-21 06:02 UTC, tisonkun commented
Thanks for your review!