[improve][broker][PIP-149]make examineMessage method async
apache/pulsar pull request #16226
Opened 2022-06-26 08:08 UTC by HQebupt

Master Issue: #14013 
### Motivation

See #14365 

### Verifying this change

Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
- [x] `doc-not-needed`

2022-06-26 09:41 UTC, HQebupt commented
/pulsarbot rerun-failure-checks

2022-06-27 02:24 UTC, Technoboy- commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> +                }).thenCompose(entry -> {
`thenApply` is more better ?

2022-06-27 02:31 UTC, Technoboy- approved these changes

2022-06-27 06:30 UTC, gaozhangmin requested changes

2022-06-27 06:30 UTC, gaozhangmin commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> +        return ret.thenCompose(__ -> validateTopicOwnershipAsync(topicName, authoritative))
`validateTopicOperationAsync` should be preceded the `getPartitionedTopicMetadataAsync`

2022-06-27 10:06 UTC, gaozhangmin approved these changes

2022-06-27 10:25 UTC, gaozhangmin commented
@Technoboy- PTAL again, changes made.

2022-06-27 11:49 UTC, merged