[improve][broker] Make splitNamespaceBundle and getTopicHashPositions async
apache/pulsar pull request #16411
Opened 2022-07-06 05:13 UTC by gaozhangmin

### Motivation

See PIP https://github.com/apache/pulsar/issues/14365 and change tracker https://github.com/apache/pulsar/issues/15043.

Make the below method async:

`getBundlesData`  `splitNamespaceBundle` `getTopicHashPositions` `setPublishRate` `getPublishRate` `setDispatchRate`

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc-not-needed`

2022-07-07 03:41 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-07 08:15 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-12 01:53 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-12 05:43 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-13 11:54 UTC, Technoboy- approved these changes

2022-07-13 16:02 UTC, nodece requested changes

2022-07-13 16:02 UTC, nodece commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
> +                        log.error("[{}] Failed to split namespace bundle {}/{} due to {}",
Log repeatedly, you should remove this line.

2022-07-13 16:02 UTC, nodece commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
> +                        log.error("[{}] Failed to split namespace bundle {}/{} due to {}",
Log repeatedly, you should remove this line.

2022-07-14 06:32 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-14 07:01 UTC, nodece approved these changes

2022-07-14 11:24 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-15 05:39 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-18 06:30 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-19 03:32 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-25 04:52 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-25 07:22 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-25 08:37 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-25 09:13 UTC, gaozhangmin commented
/pulsarbot run-failure-checks

2022-07-25 09:15 UTC, merged