[fix][io-quickstart][docs] Corrected split sentence in tip
apache/pulsar pull request #16501
Opened 2022-07-09 22:19 UTC by mans2singh

### Motivation

* The tip section contained partial sentence  `The JDBC sink connector pulls messages from Pulsar topics `.  The rest of the sentence `and persists the messages to ClickHouse, MariaDB, PostgreSQL, or SQlite. ` was below the tip section.

### Modifications

* Moved partial sentence out to the tip section.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [x] `doc` 
This PR is documentation correction.

- [ ] `doc-complete`
(Docs have been already added)

2022-07-11 00:43 UTC, codelipenghui approved these changes

2022-07-11 01:42 UTC, Anonymitaet requested changes
Thanks for your contribution! Have you previewed your changes to ensure everything goes as expected? 

If not yet, please [preview your changes locally](https://github.com/apache/pulsar-site/tree/main/site2/website-next#local-preview) and attach the screenshots in the PR description to let others know. In this way, you can get your PR merged more quickly. Thanks!

>>>>

Seems that you need to put this sentence into the `tip`

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/50226895/178173133-f062ef9e-b06a-4117-9c03-b38950037095.png">

2022-07-12 23:35 UTC, mans2singh commented
Hi @Anonymitaet :  I have moved the line into the tip block as you had recommended.  

Here is the how it looks:
<img width="1373" alt="PloQs2" src="https://user-images.githubusercontent.com/8467404/178615767-af088066-4f9d-45cf-b117-a7f1d562f27c.png">

Please let me know if you have any other advice.  Thanks

2022-07-13 01:56 UTC, Anonymitaet approved these changes

2022-07-14 01:39 UTC, merged

2022-07-14 13:06 UTC, mans2singh commented
Thanks @Anonymitaet .