Rename Pulsar txn metrics to specify OpenMetrics
apache/pulsar pull request #16581
Opened 2022-07-13 15:59 UTC by Shoothzj

### Motivation
See https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md
A COUNTER needs `metrics_name_total` or `metrics_name_created`

This PR contains metric name broken changes.

### Modifications
Rename counter's `_count` to `_total`

### metrics name broken changes
- rename `pulsar_txn_committed_count` to `pulsar_txn_committed_total`
- rename `pulsar_txn_aborted_count` to `pulsar_txn_aborted_total`
- rename `pulsar_txn_created_count` to `pulsar_txn_created_total`
- rename `pulsar_txn_timeout_count` to `pulsar_txn_timeout_total`
- rename `pulsar_txn_append_log_count` to `pulsar_txn_append_log_total`

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc-required` 
As mentioned above, the metrics name has changed

2022-07-13 16:02 UTC, codelipenghui approved these changes

2022-07-13 19:39 UTC, nicoloboschi requested changes
This is a breaking change. If we really want to go with this path we should keep both the versions, deprecate the older ones and eventually remove them in a future version

2022-07-14 02:37 UTC, michaeljmarshall approved these changes
LGTM.

@nicoloboschi - you are correct that this is a breaking change. @Shoothzj proposed this change on the mailing list: https://lists.apache.org/thread/ojwn2l2rtp4lyyrjbhmnf0m6cprjfwx8. The thread mentions that upgrading the prometheus client depends up fixing counters that do not end with `_total`. We have already merged https://github.com/apache/pulsar/pull/13785.  I don't think we can easily make it work to expose both metrics, so as long as we communicate to our users, I think this is okay.

2022-07-14 06:15 UTC, Shoothzj commented
/pulsarbot run-failure-checks

2022-07-14 09:27 UTC, nicoloboschi approved these changes
Thanks @michaeljmarshall for pointing the ML discussion.
I agree that sooner or later we have to move to newer versions of Prometheus and it's better to rename all the needed metrics in the same release

2022-07-14 09:34 UTC, Shoothzj commented
@nicoloboschi I will follow up on this. Ensure all the metrics to be renamed before 2.11.0

2022-07-14 09:34 UTC, Shoothzj commented
/pulsarbot run-failure-checks

2022-07-14 10:13 UTC, eolivelli approved these changes

2022-07-14 15:22 UTC, Shoothzj commented
/pulsarbot run-failure-checks

2022-07-15 00:53 UTC, Shoothzj commented
/pulsarbot run-failure-checks

2022-07-15 01:30 UTC, Shoothzj commented
/pulsarbot run-failure-checks

2022-07-15 01:35 UTC, merged