[improve][broker]improve the efficiency of creating topic
apache/pulsar pull request #16970
Opened 2022-08-07 09:15 UTC by HQebupt

### Motivation
The topic creating rate is less than 200 QPS  when the topic count of the namespace is about 200,000.
It is due to the time cost of topic exist checking. All the topics would be checked one by one in `org.apache.pulsar.broker.admin.AdminResource#checkTopicExistsAsync`. As the count of topic grows in a namespace, this method will take a lot.

### Modifications
use `org.apache.pulsar.broker.namespace.NamespaceService#checkTopicExists` to check if the topic is exist because this method is more efficient.

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.
### Does this pull request potentially affect one of the following parts:

If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
- [x] `doc-not-needed`

2022-08-07 13:39 UTC, poorbarcode approved these changes

2022-08-08 02:49 UTC, codelipenghui requested changes
This will change the behavior, no?

The `checkTopicExists` only check the managed ledger is existing or not, but doesn't check if the partitioned topics are with the same topic name.

2022-08-08 02:51 UTC, codelipenghui commented
Here is a related ML discussion https://lists.apache.org/thread/2b3bn6f2sw7m6x0pwx1dkk42q8pp3p8n

2022-12-06 10:19 UTC, tisonkun commented
Closed as stale. Feel free to rebase and resubmit the patch.

2022-12-06 10:19 UTC, closed without merging