[doc][monitoring][metadata] metadata store metrics doc
apache/pulsar pull request #17088
Opened 2022-08-14 12:16 UTC by tjiuming

### Motivation

doc for https://github.com/apache/pulsar/pull/17041

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

2022-08-22 09:59 UTC, Anonymitaet approved these changes
Thanks for your contribution! Approved from the technical writing perspective. 😊

2022-09-20 11:03 UTC, codelipenghui requested changes
@tjiuming I think you need update this PR according to PR https://github.com/apache/pulsar/pull/17041

2022-09-20 12:55 UTC, tjiuming commented
> @tjiuming I think you need update this PR according to PR #17041

@codelipenghui updated

2022-09-22 10:30 UTC, codelipenghui approved these changes

2022-09-22 10:30 UTC, merged