[fix][sec] bump snakeyaml to 1.31 fix CVE-2022-25857
apache/pulsar pull request #17457
Opened 2022-09-05 00:12 UTC by tisonkun

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)

Fix CVE/

- [x] `doc-not-needed`

2022-09-05 00:18 UTC, Shoothzj approved these changes

2022-09-05 00:20 UTC, tisonkun commented
This patch can still fail on OWASP due to CVE-2021-3565 fp. See the report for details or see #17458 as a batch patch.

2022-09-05 01:09 UTC, zymap requested changes
Thank you! Please help to update the license file for [pulsar](https://github.com/apache/pulsar/blob/d139d884bcf38d8d9f2ff99bb355591819b85ef5/distribution/server/src/assemble/LICENSE.bin.txt#L457) and lib/presto as well.

2022-09-05 01:17 UTC, tisonkun commented
@zymap nice catch! Updated.

2022-09-05 01:19 UTC, zymap approved these changes

2022-09-05 01:19 UTC, zymap commented
Thank you!

2022-09-05 02:34 UTC, Technoboy- approved these changes

2022-09-05 03:16 UTC, tisonkun commented
/pulsarbot run-failure-checks

2022-09-05 03:59 UTC, Jason918 approved these changes

2022-09-05 04:04 UTC, tisonkun commented
@zymap @Technoboy- @Jason918 This patch is ready to merge. Then I'll rebase #17458 onto this one :)

2022-09-05 04:10 UTC, merged

2022-09-18 10:15 UTC, pjfanning commented
snakeyaml v1.32 fixes a 2nd similar issue - https://github.com/advisories/GHSA-9w3m-gqgf-c4p9

2022-11-15 02:32 UTC, tisonkun commented
@congbobo184 I think I can pick only #17779 that bump to 1.32. I'm doing this now :)