[improve][broker] Add gzip compression support for /metrics endpoint
apache/pulsar pull request #18102
Opened 2022-10-19 05:40 UTC by xuesongxs

Fixes #16321

Replace the PR: https://github.com/apache/pulsar/pull/16888

2022-10-19 15:13 UTC, asafm requested changes
Documentation is auto-generated from the annotations?

2022-10-19 15:13 UTC, asafm commented on pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
> +    private boolean compressOutputMetricsInPrometheus = false;
It's not really in Prometheus, so maybe `compressPrometheusMetricsOutput`?

2022-10-20 01:32 UTC, xuesongxs commented on pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
> +            doc = "Enable or disable compress output metrics in prometheus"
> Since it's only Gzip, let's write it?

The rest of the work will be left to you.

2022-10-20 12:52 UTC, asafm commented on pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
> +            doc = "Enable or disable compress output metrics in prometheus"
`Enable or disable compress output metrics in prometheus` --> `Enable or disable GZip compression of Prometheus metrics endpoint response`

2022-11-23 08:00 UTC, lhotari commented
Regarding the comment by @asafm in https://github.com/apache/pulsar/pull/16888#issuecomment-1233894144 , I think that all endpoints would benefit of compression. Having the compression support doesn't mean that the response will always be compressed, it's only if the client sends a `Accept-Encoding: gzip` header.

2023-11-28 11:32 UTC, hangc0276 commented
I tested the Prometheus metric with 1000 topics and enabled the compression to get 33x data saving.
```
# curl -H 'Accept-Encoding: gzip' -o kk0.log.gz http://localhost:8080/metrics/ 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  927k    0  927k    0     0  1910k      0 --:--:-- --:--:-- --:--:-- 1941k
# curl -o kk1.log http://localhost:8080/metrics/  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33.2M    0 33.2M    0     0  73.1M      0 --:--:-- --:--:-- --:--:-- 74.4M
# ll -lrt |grep kk
-rw-r--r--     1 hangc  staff   928K Nov 28 18:46 kk0.log.gz
-rw-r--r--     1 hangc  staff    33M Nov 28 18:46 kk1.log
```

Due to the response being compressed according to the client request header, I think we can add the GzipHandler for all the endpoints instead of the metric endpoint.

However, the Prometheus server sends a fetch metric request with `Accept-Encoding: gzip` header, which will fetch the metrics with compression. https://github.com/prometheus/prometheus/issues/12319. It may cause the Prometheus server to run into high CPU usage. https://github.com/prometheus/blackbox_exporter/issues/270. 

For the master branch of Prometheus supports disabling compression in the client request header https://github.com/prometheus/prometheus/pull/13166, I'm not sure if we need to add a flag to control whether the Pulsar HTTP server supports compression or not.  @lhotari @asafm @codelipenghui Do you guys have any ideas?

2023-11-28 11:32 UTC, hangc0276 commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java
> +        assertEquals(response.getHeaders().get("Content-Encoding"), "gzip");
We need to test the response payload at the same time.

2023-11-28 11:59 UTC, hangc0276 commented
@xuesongxs Please rebase the master.

2023-11-28 12:01 UTC, hangc0276 commented on conf/broker.conf
> +# Set the minimum response size to trigger dynamic compression. The default value is 32.
Can we use the default value and remove this configuration?

2023-11-28 12:01 UTC, hangc0276 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
> +                        config.isAuthenticationEnabled(), attributeMap, false);
Can we apply this GzipHandle support for all the endpoints instead of the metric endpoint? It will benefit for all the REST response.

2023-11-29 11:18 UTC, asafm commented
> I tested the Prometheus metric with 1000 topics and enabled the compression to get 33x data saving.
> 
> ```
> # curl -H 'Accept-Encoding: gzip' -o kk0.log.gz http://localhost:8080/metrics/ 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  927k    0  927k    0     0  1910k      0 --:--:-- --:--:-- --:--:-- 1941k
> # curl -o kk1.log http://localhost:8080/metrics/  
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 33.2M    0 33.2M    0     0  73.1M      0 --:--:-- --:--:-- --:--:-- 74.4M
> # ll -lrt |grep kk
> -rw-r--r--     1 hangc  staff   928K Nov 28 18:46 kk0.log.gz
> -rw-r--r--     1 hangc  staff    33M Nov 28 18:46 kk1.log
> ```
> 
> Due to the response being compressed according to the client request header, I think we can add the GzipHandler for all the endpoints instead of the metric endpoint.
> 
> However, the Prometheus server sends a fetch metric request with `Accept-Encoding: gzip` header, which will fetch the metrics with compression. [prometheus/prometheus#12319](https://github.com/prometheus/prometheus/issues/12319). It may cause the Prometheus server to run into high CPU usage. [prometheus/blackbox_exporter#270](https://github.com/prometheus/blackbox_exporter/issues/270).
> 
> For the master branch of Prometheus supports disabling compression in the client request header [prometheus/prometheus#13166](https://github.com/prometheus/prometheus/pull/13166), I'm not sure if we need to add a flag to control whether the Pulsar HTTP server supports compression or not. @lhotari @asafm @codelipenghui Do you guys have any ideas?

Since `io.prometheus.client.exporter.HTTPServer` supports returning compresses responses based on headers, Pulsar shouldn't be different.

2023-11-29 11:19 UTC, asafm commented
I still have pending comments from 2022 @hangc0276 :)

2024-02-27 10:07 UTC, lhotari commented
Replaced by #21667

2024-02-27 10:07 UTC, closed without merging