[cleanup][general] Use correct Guava imports
apache/pulsar pull request #18113
Opened 2022-10-19 09:47 UTC by nahguam

### Motivation

Some usages of Guava are coming from the version shaded in Curator.

### Modifications

* Use the correct Guava imports.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/nahguam/pulsar/pull/3

2022-10-19 10:23 UTC, nodece approved these changes

2022-10-21 15:39 UTC, nicoloboschi requested changes
Thanks! Could you add that package in the forbidden imports to avoid "regressions" ? 

https://github.com/apache/pulsar/blob/1d6824cdbed45c8f6ad0b160f0e23b2447e0620c/buildtools/src/main/resources/pulsar/checkstyle.xml#L140

2022-10-21 15:48 UTC, nahguam commented
> Thanks! Could you add that package in the forbidden imports to avoid "regressions" ?
> 
> https://github.com/apache/pulsar/blob/1d6824cdbed45c8f6ad0b160f0e23b2447e0620c/buildtools/src/main/resources/pulsar/checkstyle.xml#L140

@nicoloboschi Nice! done :)

2022-10-21 17:35 UTC, nicoloboschi approved these changes

2022-10-22 06:11 UTC, merged