[improve][ci] skip CI cronjob in forks
apache/pulsar pull request #18411
Opened 2022-11-10 09:23 UTC by tisonkun

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

2022-11-10 09:56 UTC, nicoloboschi approved these changes
good catch! 
I didn't realized the schedule would run in every single fork of Pulsar every day, that is such a waste of GH resources.

2022-11-10 10:08 UTC, tisonkun commented
@nicoloboschi Thanks for your review! I push one more commit e861b6bda23bd010fd5cd34ee381c6ac8eff9f75 to skip the always running `pulsar-ci-checks-completed` job. I'm unsure whether it's the proper way, perhaps we can alternatively check the `needs.*.result` but I found the pushed way is shorter.

2022-11-10 12:36 UTC, tisonkun commented
/pulsarbot run-failure-checks

2022-11-10 12:36 UTC, tisonkun commented
It's ready to merge.

cc @lhotari @nicoloboschi please take a look.

2022-11-10 14:49 UTC, nicoloboschi requested changes

2022-11-10 14:49 UTC, nicoloboschi commented on .github/workflows/pulsar-ci.yaml
> +    if: ${{ !cancelled() }}
I'm not sure. If I cancel the workflow manually then this job is marked as skipped and then GH allows me merge the pull. Could you verify it ?

2022-11-10 15:32 UTC, tisonkun commented
@nicoloboschi You're right. I recover the `always() && ...` pattern and it seems the issue you reported vanished.

If we can reach a consensus on this version, let's see how the next cronjob works :)

2022-11-11 06:45 UTC, tisonkun commented
ping @nicoloboschi @lhotari

2022-11-11 12:35 UTC, lhotari approved these changes

2022-11-11 12:36 UTC, nicoloboschi approved these changes

2022-11-11 12:36 UTC, lhotari commented
/pulsarbot rerun-failure-checks

2022-11-11 14:34 UTC, tisonkun commented
Thanks for your reviews! Merging...

2022-11-11 14:34 UTC, merged