[fix][fn] Make KubernetesRuntime translate characters in function tenant, namespace, and name during function removal to avoid label errors
apache/pulsar pull request #19584
Opened 2023-02-21 19:13 UTC by csthomas1

Make KubernetesRuntime translate tenant, namespace, and function name characters that are not allowed within Kubernetes labels as part of function removal.

Fixes #19583 

### Motivation

See linked issue ticket.

### Modifications

Updated KubernetesRuntime.deleteStatefulSet() to pass function tenant, namespace, and name values through the pre-existing getLabels() function to replace disallowed characters.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

2023-04-05 06:34 UTC, lhotari approved these changes
LGTM, thanks for the contribution!

2023-04-05 06:35 UTC, lhotari commented
Closing and reopening to get a new build with a fresh merge commit for master branch in the build.

2023-04-05 07:23 UTC, nicoloboschi requested changes
good catch! would you mind to add a test case?

2023-04-06 12:29 UTC, csthomas1 commented
Sure!

On Wed, Apr 5, 2023 at 3:24 AM Nicolò Boschi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> good catch! would you mind to add a test case?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/pulsar/pull/19584#pullrequestreview-1372300502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5QVSJOBEJ2NX5I3JWJL4DW7UMZRANCNFSM6AAAAAAVDNP4DI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-10 10:34 UTC, nicoloboschi approved these changes

2023-05-10 10:34 UTC, lhotari commented
Closing and re-opening to trigger a new CI build with changes from master branch.

2023-06-13 01:36 UTC, tisonkun approved these changes

2023-06-13 04:35 UTC, tisonkun commented
Merging...

Thank you!

2023-06-13 04:35 UTC, merged