[fix][client] Broker address resolution wrong if connect through a multi-dns names proxy
apache/pulsar pull request #19597
Opened 2023-02-22 11:03 UTC by nicoloboschi

### Motivation

Regression of https://github.com/apache/pulsar/pull/19327
in the client, to understand if is connected through a proxy, it checks the logical address vs the physical one, if they're different it supposes it has to target that specific broker passing through the proxy.

In the above pull request, the comparison logic is changed and the logical address is compared to ONE of the resolved dns names. in case of multiple dns names of the proxy, it might happens that the first resolved dns name doesn't match with the logical proxy address and therefore it's considered to be a broker dns name.
This leads to the proxy to recursive send connections to itself.

These are some logs extracted: 
```
11:02:35.141 [pulsar-client-io-2-1] INFO  org.apache.pulsar.client.impl.PulsarChannelInitializer - initializeClientCnx DEBUG pulsar-proxy:6651, pulsar-proxy.pcert.svc.cluster.local:6651                                                                                                                                                                              
11:02:35.147 [pulsar-client-io-2-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0xce7e9e49, L:/10.42.0.247:41194 - R:pulsar-proxy.pcert.svc.cluster.local/10.43.217.3:6651]] Connected to server                                                                                                                                                        11:02:35.172 [pulsar-client-io-2-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0xce7e9e49, L:/10.42.0.247:41194 - R:pulsar-proxy.pcert.svc.cluster.local/10.43.217.3:6651] Connected through proxy to target broker at pulsar-proxy:6651
```

### Modifications

* Revert the comparison logic changes while keeping the improvements of https://github.com/apache/pulsar/pull/19327

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

2023-02-22 16:09 UTC, michaeljmarshall approved these changes
Great work @nicoloboschi! Thank you for fixing this!

2023-02-22 17:21 UTC, michaeljmarshall commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java
> +                                                   InetSocketAddress unresolvedPhysicalAddress) {
We were using this address for `cnx.setRemoteHostName(...);` before. In order to maintain consistency, I think we should consider doing that in this PR too.

2023-02-22 19:46 UTC, michaeljmarshall requested changes
Requesting changes since I think we need to get the hostname right for the `setRemoteHostName` method.

2023-02-23 07:15 UTC, nicoloboschi commented
> Requesting changes since I think we need to get the hostname right for the `setRemoteHostName` method.

Good point! I've fixed it PTAL

2023-02-23 07:46 UTC, michaeljmarshall approved these changes
LGTM

2023-02-23 09:12 UTC, merged