[Branch-2.11] Revert [improve][broker] Require authRole is proxyRole to set originalPrincipal(#19455)
apache/pulsar pull request #19820
Opened 2023-03-15 07:25 UTC by hangc0276

This reverts commit c7eabc9391361508fc222469479bfea83d5d0c64.

### Motivation
PR #19455 introduced break change and has been cherry-picked to release branch-2.11. It will lead to users upgrading to the new release version authenticate failed.

### Modifications

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

2023-03-15 07:56 UTC, nodece approved these changes
LGTM

2023-03-15 08:00 UTC, Technoboy- approved these changes

2023-03-15 08:49 UTC, hangc0276 commented
We need to revert more commits related to this PR.

2023-03-15 14:40 UTC, mattisonchao approved these changes

2023-03-15 14:47 UTC, michaeljmarshall requested changes
> We need to revert more commits related to this PR.

Even if the PMC decides that the right decision is to "revert this behavior change", we should not revert this whole commit. Only a few lines of code are actually under dispute.

2023-03-15 14:47 UTC, michaeljmarshall commented on pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java
> -        }
These are the lines that are under question.

2023-03-16 03:57 UTC, codelipenghui commented
We have an acceptable solution for now. So that we don't need to revert this change, just push a fix to the release branches.
https://lists.apache.org/thread/q1k1krfjr8njdf8t3sy1ht4vg67s4x71 the discussion thread.

And @michaeljmarshall message me in Slack, he will open PR to fix it.

Thanks @hangc0276 and @michaeljmarshall

2023-03-16 05:51 UTC, michaeljmarshall commented
https://github.com/apache/pulsar/pull/19830 should supersede this PR, so I am going to close this for now.

2023-03-16 05:51 UTC, closed without merging