[improve][pulsar-shell] Use singleton custom command factories
apache/pulsar pull request #20064
Opened 2023-04-10 23:58 UTC by aymkhalil

Fixes #20061

### Motivation

Loads custom factories in pulsar shell only once because multiple loads are redundant, and the lifecycle of classes in the NAR class loader (child) and the App Class Loader (parent) could be out of sync if the custom command has a dependency that is available on the parent loader. In this case, the "dependent" class will be recycled between the shell commands, but not the "dependency" class which could lead to leaking static resources.

### Modifications

Made the logic to load the custom command factory singleton

### Verifying this change

- [X] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests and can be verified as follows:
  - Added `customCommandsFactorySingleton` unit test to verify singleton property 
  - [manual] Did manual testing locally with a scenario that has a dependency on the parent class loader

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/aymkhalil/pulsar/pull/6

2023-04-11 08:15 UTC, nicoloboschi requested changes

2023-04-11 08:15 UTC, nicoloboschi commented on pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
> +    protected static List<CustomCommandFactory> customCommandFactories;
In pulsar shell a new instance of PulsarAdminTool (actually AdminShell) is created when the current config changes.
I think it's fine to just cache it locally to the instance and remove `static`

2023-04-12 12:10 UTC, tisonkun approved these changes
LGTM.

ping @nicoloboschi may take another look

2023-04-12 13:09 UTC, nicoloboschi approved these changes

2023-04-12 13:09 UTC, merged