[imporve] [broker] Add log on topic or subscription when enable rate limit.
apache/pulsar pull request #20660
Opened 2023-06-27 11:40 UTC by lifepuzzlefun

Fixes #xyz

Main Issue: #xyz

PIP: #xyz 

### Motivation

### Modifications

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

2023-06-28 03:41 UTC, gaoran10 approved these changes

2023-07-05 08:23 UTC, coderzc approved these changes

2023-07-05 12:48 UTC, Technoboy- commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
> +                        new DispatchRateLimiter(topic, cursor.getName(), Type.REPLICATOR));
`Codec.decode(cursor.getName())`

2023-07-05 12:48 UTC, Technoboy- requested changes
`Codec.decode(cursor.getName())`

2023-07-07 17:12 UTC, lifepuzzlefun commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
> +                        new DispatchRateLimiter(topic, cursor.getName(), Type.REPLICATOR));
aha, fixed

2023-07-13 02:01 UTC, Technoboy- approved these changes

2023-07-13 02:01 UTC, merged