[fix][sec] Upgrade Guava to 32.0.1 to address CVE-2023-2976
apache/pulsar pull request #20699
Opened 2023-06-30 17:12 UTC by poorbarcode

### Motivation

The PR https://github.com/apache/pulsar/pull/20459 was addressed CVE-2023-2976 3 weeks ago

In the doc of https://github.com/advisories/GHSA-7g45-4rm6-3mm3, the version `32.0.1` is suggested now

### Modifications

Upgrade Guava to 32.0.1

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: x

2023-07-01 01:06 UTC, Technoboy- approved these changes

2023-07-03 15:31 UTC, lhotari requested changes
Please use version `32.1.1-jre` since `32.0.1-jre` has broken Gradle metadata. See https://github.com/google/guava/releases

2023-07-04 09:17 UTC, poorbarcode commented
@lhotari 

>Please use version 32.1.1-jre since 32.0.1-jre has broken Gradle metadata. See https://github.com/google/guava/releases

FIxed, please take a look again, thanks

2023-07-04 09:28 UTC, lhotari approved these changes
LGTM

2023-07-04 13:48 UTC, Shoothzj approved these changes

2023-07-05 04:17 UTC, merged