[fix][broker] Intercept all commands
apache/pulsar pull request #21265
Opened 2023-09-28 04:57 UTC by kecona

### Motivation

`org.apache.pulsar.broker.intercept.BrokerInterceptor#onPulsarCommand` should intercept all incoming commands.

### Modifications

- Call `safeInterceptCommand()` to intercept the command before handing the command

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

2023-09-28 08:14 UTC, Jason918 commented on pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
> +                handlePartitionMetadataRequest(cmd.getPartitionMetadata());
This is a behavior change if `InterceptException` is thrown from `interceptCommand`. This may cause client stuck if it can't get the error.

2023-10-07 02:06 UTC, liudezhi2098 approved these changes

2023-10-08 08:40 UTC, Jason918 commented on pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
> +                handlePartitionMetadataRequest(cmd.getPartitionMetadata());
> The `safeInterceptCommand()` method catches the `Exception`, it is safe.

Yes, it catch the exception, but it seems there is no `writeAndFlush` in `safeInterceptCommand`. The behavior is different to clients.

2023-10-16 13:04 UTC, codelipenghui requested changes
The PulsarDecoder is used by the Server and Client. 

For example:

CLOSE_CONSUMER, the broker side will not receive this command.

We should list the missed commands first instead of "Intercept all commands".

2023-10-17 02:43 UTC, kecona commented
Hi all, this PR has been changed to only intercept the `REDELIVER_UNACKNOWLEDGED_MESSAGES` command.

2023-10-18 09:43 UTC, Jason918 approved these changes
LGTM

2023-10-18 12:07 UTC, kecona commented
/pulsarbot rerun-failure-checks

2023-10-23 11:27 UTC, codelipenghui reviewed
The change looks good to me now.

Could you please add a test to avoid regression?
BrokerInterceptorTest should be a good place.

2023-10-24 01:41 UTC, kecona commented
Do we cherry-pick this PR to Pulsar 2.10, Pulsar 2.11 and Pulsar 3.0?

2023-10-25 01:36 UTC, kecona commented
/pulsarbot rerun-failure-checks

2023-10-25 08:18 UTC, kecona commented
/pulsarbot rerun-failure-checks

2023-10-25 14:49 UTC, codelipenghui approved these changes

2023-10-25 14:49 UTC, merged