[fix][broker] Fix potential NPE when disabling the liveness check
apache/pulsar pull request #21840
Opened 2024-01-03 08:55 UTC by mattisonchao

### Motivation

Fix potential NPE when disabling the liveness check

### Modifications

- Fix potential NPE when disabling the liveness check

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

2024-01-03 09:35 UTC, RobertIndie approved these changes
LGTM.

Just want to make sure. The NPE will only be thrown here:
https://github.com/apache/pulsar/blob/c4cff0ab3dac169c0a1418ef2f63f61604f6278e/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java#L971 Right?

2024-01-03 11:35 UTC, Technoboy- approved these changes

2024-01-03 12:18 UTC, lhotari requested changes
I think that there was a reason to return null when this was implemented. Please postpone merging until I have reviewed this.

2024-01-03 12:20 UTC, lhotari commented
@mattisonchao is there a way to have a test case for this?

2024-01-03 13:41 UTC, Technoboy- commented
> @mattisonchao is there a way to have a test case for this?

I don't think we need this kind of test, the method should return `Boolean`, not `null`.

2024-01-04 03:31 UTC, dao-jun commented
LGTM, but also need to remove the null checker?
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java#L173

2024-01-05 17:44 UTC, lhotari commented
I now had a chance to review the reason why I had originally used `null`. 
It's documented here: https://github.com/apache/pulsar/blob/c4cff0ab3dac169c0a1418ef2f63f61604f6278e/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java#L80-L87

I'll suggest that we change the return value from `CompletableFuture<Boolean>` to `CompletableFuture<Optional<Boolean>>` if there's a desire to get rid of the special `null` usage. 
@mattisonchao Could you make this change?

2024-01-08 01:38 UTC, Technoboy- commented
> I now had a chance to review the reason why I had originally used `null`. It's documented here:
> 
> https://github.com/apache/pulsar/blob/c4cff0ab3dac169c0a1418ef2f63f61604f6278e/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java#L80-L87
> 
> I'll suggest that we change the return value from `CompletableFuture<Boolean>` to `CompletableFuture<Optional<Boolean>>` if there's a desire to get rid of the special `null` usage. @mattisonchao Could you make this change?

if `null` means disable, then we find a bug here 
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java#L173

2024-01-08 01:45 UTC, Technoboy- commented
> I now had a chance to review the reason why I had originally used `null`. It's documented here:
> 
> https://github.com/apache/pulsar/blob/c4cff0ab3dac169c0a1418ef2f63f61604f6278e/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java#L80-L87
> 
> I'll suggest that we change the return value from `CompletableFuture<Boolean>` to `CompletableFuture<Optional<Boolean>>` if there's a desire to get rid of the special `null` usage. @mattisonchao Could you make this change?

ok, then we find a new place need to fix to avoid NPE
https://github.com/apache/pulsar/blob/cea5c931b43cbc5181aaa79dfee09d53cc1389d1/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java#L958-L979

2024-01-08 06:13 UTC, lhotari approved these changes

2024-01-08 13:00 UTC, merged

2024-01-11 11:55 UTC, lhotari commented
> 2. In my opinion, if we turned off the connection liveness check, that logic should be equal to the connection always being alive. 

I disagree. That would be bad API design. There might be future use cases where this matters.