[improve][pip] PIP-331: Replace configuration `brokerServiceCompactionPhaseOneLoopTimeInSeconds` with `brokerServiceCompactionPhaseOneMessageReadTimeoutInSeconds`
apache/pulsar pull request #21910
Opened 2024-01-17 07:49 UTC by thetumbled

### Motivation

A PIP proposal to replace configuration `brokerServiceCompactionPhaseOneLoopTimeInSeconds` with `brokerServiceCompactionPhaseOneMessageReadTimeoutInSeconds`.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

2024-01-17 11:48 UTC, BewareMyPower requested changes
Actually I don't think introducing such a config is meaningful, unless you can explain in which case will users to modify this config? Pulsar has too many configs, which is very unfriendly. i.e. I wouldn't approve https://github.com/apache/pulsar/pull/11206 if I reviewed it.

2024-01-18 01:42 UTC, thetumbled commented
> Actually I don't think introducing such a config is meaningful, unless you can explain in which case will users to modify this config? Pulsar has too many configs, which is very unfriendly. i.e. I wouldn't approve #11206 if I reviewed it.

This pip is just to correct the ambiguous configuration name and doc. 
As for the meaning of this conf, we actually do not modify this config most of the time. But compare with reserving this  misleading conf, we'd better fix it.

2024-01-19 08:30 UTC, BewareMyPower commented
I support fixing the config documentation, which does not require a PIP. But I don't support adding a new config for that.

2024-01-19 08:46 UTC, thetumbled commented
> I support fixing the config documentation, which does not require a PIP. But I don't support adding a new config for that.

+1

2024-01-20 00:15 UTC, thetumbled commented
closed for the discussion above.

2024-01-20 00:15 UTC, closed without merging