[improve][broker] Change log level to reduce duplicated logs
apache/pulsar pull request #22147
Opened 2024-02-28 09:08 UTC by mattisonchao

### Motivation

Some vendors' environments do not support reading virtual NIC type. The broker will constantly print the useless warning log, which will increase the storage cost.  

The demo logs is as follows:

```
 [pulsar-load-manager-1-1] WARN  org.apache.pulsar.broker.loadbalance.LinuxInfoUtils - [LinuxInfo] Failed to read /sys/class/net/nc1 NIC type, the detail is: /sys/class/net/nc1/type: Not a directory
 [pulsar-load-manager-1-1] WARN  org.apache.pulsar.broker.loadbalance.LinuxInfoUtils - [LinuxInfo] Failed to read /sys/class/net/nc1 NIC type, the detail is: /sys/class/net/nc1/type: Not a directory
[pulsar-load-manager-1-1] WARN  org.apache.pulsar.broker.loadbalance.LinuxInfoUtils - [LinuxInfo] Failed to read /sys/class/net/nc1 NIC type, the detail is: /sys/class/net/nc1/type: Not a directory
```

### Modifications

- Because this is the judgement of boolean. It's okay to move the log to be debug level.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

2024-02-28 09:54 UTC, asafm commented
@mattisonchao Can you explain why this log is printed so many times?

2024-02-28 18:48 UTC, lhotari requested changes
In this case, the file doesn't even seem to exist. Could we avoid the exception in the first place by checking with java.nio.file.Files#isReadable if the file exists and is readable? Does Files.isReadable check work for these special `/sys/class/net` files?

2024-02-29 01:19 UTC, mattisonchao commented
> @mattisonchao Can you explain why this log is printed so many times?

Because the broker needs to report the load data constantly and then this judgement method will invoke many times. :)

https://github.com/apache/pulsar/blob/3b3c713192ba43a594090d487289fb4d665d2f4c/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java#L276

2024-02-29 01:28 UTC, mattisonchao commented
>In this case, the file doesn't even seem to exist. Could we avoid the exception in the first place by checking with java.nio.file.Files#isReadable if the file exists and is readable? Does Files.isReadable check work for these special /sys/class/net files?

This method is only used to judge whether the current NIC is physical. IMO, the exception status also means not a valid physical NIC. I think giving it a debug-level log for troubleshooting is enough.

And yes, we can give an extra operation to check if the current file type exists. but for the other exceptions, we still need to not print logs in the warn or error level to avoid annoying logs.

2024-02-29 13:29 UTC, dao-jun approved these changes

2024-02-29 15:27 UTC, lhotari commented
> >In this case, the file doesn't even seem to exist. Could we avoid the exception in the first place by checking with java.nio.file.Files#isReadable if the file exists and is readable? Does Files.isReadable check work for these special /sys/class/net files?
> 
> This method is only used to judge whether the current NIC is physical. IMO, the exception status also means not a valid physical NIC. I think giving it a debug-level log for troubleshooting is enough.
> 
> And yes, we can give an extra operation to check if the current file type exists. but for the other exceptions, we still need to not print logs in the warn or error level to avoid annoying logs. 
> 
> cc @lhotari 

I think it's better to avoid exceptions and add a file existence check since we are touching this part of the code.

2024-03-01 14:26 UTC, mattisonchao commented
Applied the comment. cc @lhotari

2024-03-01 14:27 UTC, lhotari approved these changes

2024-03-10 14:07 UTC, merged