[fix][client] Fix ReaderBuilder doest not give illegalArgument on connection failure retry
apache/pulsar pull request #22639
Opened 2024-05-02 23:17 UTC by rdhabalia

Fixes #22638

### Motivation

Currently when Reader Builder is used to create Reader with `startMessageFromRollbackDuration` and if it fails due to connection issue and application retries to create a new Reader again then it throws IllegalArgument Exception even though Reader doesn't have any incorrect argument and that confuses the users.

### Modifications

Application should be able to retry and able to recreate Reader using the ReaderBuilder if it fails due to connection issue.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

2024-05-02 23:44 UTC, dao-jun requested changes

2024-05-02 23:44 UTC, dao-jun commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderBuilderImpl.java
> +        if (isStartMsgIdExist && conf.getStartMessageFromRollbackDurationInSec() > 0
```java
        if ((isStartMsgIdExist && conf.getStartMessageFromRollbackDurationInSec() > 0)
                || (conf.getStartMessageId() == null && conf.getStartMessageFromRollbackDurationInSec() <= 0)) {
            return FutureUtil
                    .failedFuture(new IllegalArgumentException(
                            "Start message id or start message from roll back must be specified but they cannot be"
                                    + " specified at the same time"));
        }
```

2024-05-08 01:47 UTC, dao-jun approved these changes

2024-05-10 11:09 UTC, lhotari approved these changes
LGTM

2024-05-10 11:10 UTC, lhotari commented
the check that needed to be revisited was added in #6392

2024-05-10 11:10 UTC, merged