[fix][test] Fix ManagedCursorTest.testForceCursorRecovery
apache/pulsar pull request #23518
Opened 2024-10-27 13:54 UTC by ZhaoGuorui666

Fixes #23417 

### Motivation
Ideally, recoverFromLedger should only call operationComplete upon successful recovery and operationFailed upon failure. However, in the actual implementation, both methods may be called due to the following reasons:

Concurrent Execution: If recoverFromLedger is executed in different threads, it may simultaneously meet both success and failure conditions, leading to both callbacks being triggered.

After adding logs, we may see both:
* Cursor recovery success
* Cursor recovery failed

### Modifications

Use an atomic variable. Use an AtomicBoolean in the callback to mark whether the callback method has already been called, preventing duplicate calls.

2024-10-28 07:46 UTC, nodece commented
Could you verify https://github.com/apache/pulsar/pull/23518/files#diff-42dd67f8328871b3f0d30446ed1a4f1856807860c5226a9ec6c4d3a9f8813428R4882? Hrere should append a `return`.

2024-10-29 03:04 UTC, ZhaoGuorui666 commented
I understand the `ManagedCursorImpl.recoverFromLedger()` called by the bottom layer of this test, which calls `Bookeeper.syncOpenLedger()` instead of `TestPulsarMockBookKeeper`

![image](https://github.com/user-attachments/assets/ee6f1171-3f34-4998-b984-9493e830c080)

![image](https://github.com/user-attachments/assets/38b08936-6c32-4b78-858e-dbd13af5193e)

2024-10-29 03:07 UTC, ZhaoGuorui666 commented
Execute 3000 times, all passed
![image](https://github.com/user-attachments/assets/ab252c30-6d50-4899-ae6a-3ff246546e82)

2024-10-30 01:51 UTC, Technoboy- approved these changes

2024-10-30 03:22 UTC, nodece commented
In this test, we are using `org.apache.bookkeeper.mledger.impl.ManagedCursorTest.TestPulsarMockBookKeeper`.

`ManagedCursorImpl.recoverFromLedger()` will call this method from that:
```
  public void asyncOpenLedger(final long lId, final DigestType digestType, final byte[] passwd,
                final OpenCallback cb, final Object ctx) {
            if (ledgerErrors.containsKey(lId)) {
                cb.openComplete(ledgerErrors.get(lId), null, ctx);
                return; // TODO: Please add a return.
            }
            super.asyncOpenLedger(lId, digestType, passwd, cb, ctx);
        }
```

It seems that the test results were affected by multiple callback calls.

2024-10-30 03:22 UTC, nodece requested changes
Left a comment.

2024-10-30 03:55 UTC, ZhaoGuorui666 commented
@nodece Thank you for your prompt and suggestion. It has been revised.

2024-10-30 05:26 UTC, ZhaoGuorui666 commented
> ```
> 2024-10-30T12:38:15,591 - ERROR - [main:ManagedCursorImpl@553] - [my_test_ledger] Error opening metadata ledger -1 for cursor c1: Bookie handle is not available
> 2024-10-30T12:38:15,592 - INFO  - [main:ManagedCursorImpl@750] - [my_test_ledger] Cursor c1 recovered to position 3:-1
> 2024-10-30T12:38:15,592 - INFO  - [main:MetaStoreImpl@257] - expectedVersion:0 [my_test_ledger] Creating consumer c1 on meta-data store with cursorsLedgerId: -1
> markDeleteLedgerId: 3
> markDeleteEntryId: -1
> lastActive: 1730263095578
> 
> 2024-10-30T12:38:15,593 - INFO  - [test-OrderedScheduler-0-0:ManagedCursorImpl@550] - [my_test_ledger] Opened ledger -1 for cursor c1. rc=-7
> 2024-10-30T12:38:15,593 - ERROR - [test-OrderedScheduler-0-0:ManagedCursorImpl@553] - [my_test_ledger] Error opening metadata ledger -1 for cursor c1: No such ledger exists on Bookies
> 2024-10-30T12:38:15,593 - INFO  - [test-OrderedScheduler-0-0:ManagedCursorImpl@750] - [my_test_ledger] Cursor c1 recovered to position 3:-1
> 2024-10-30T12:38:15,593 - INFO  - [test-OrderedScheduler-0-0:MetaStoreImpl@257] - expectedVersion:0 [my_test_ledger] Creating consumer c1 on meta-data store with cursorsLedgerId: -1
> markDeleteLedgerId: 3
> markDeleteEntryId: -1
> lastActive: 1730263095578
> 
> 2024-10-30T12:38:15,601 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:ManagedCursorImpl$25@2772] - ledger.getStore().asyncUpdateCursorInfo operation complete
> 2024-10-30T12:38:15,602 - WARN  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:ManagedCursorImpl$25@2779] - [my_test_ledger] Failed to update cursor metadata for c1 due to version conflict org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException:
> 
> java.lang.AssertionError:
> Expected :true
> Actual   :false
> <Click to see difference>
> 
> 
> 	at org.testng.Assert.fail(Assert.java:110)
> 	at org.testng.Assert.failNotEquals(Assert.java:1577)
> 	at org.testng.Assert.assertTrue(Assert.java:56)
> 	at org.testng.Assert.assertTrue(Assert.java:66)
> 	at org.apache.bookkeeper.mledger.impl.ManagedCursorTest.testForceCursorRecovery(ManagedCursorTest.java:4858)
> ```
> 
> From the log of failed test, we can see `expectedVersion:0 [my_test_ledger] Creating consumer c1 on meta-data store with cursorsLedgerId: -1` twice. The root cause of this flaky test is we **call the cb.openComplete() twice**, which may cause race condition: when the first cursorInfo has not been saved, the second update cursorInfo started use the oldVersion, so when to save the second cursorInfo meta, it will throw BadVersion exception
> 
> So We don't need to add `AtomicBoolean callbackInvoked = new AtomicBoolean(false);`, we can just fix this to add return in TestPulsarMockBookKeeper.asyncOpenLedger or add else like
> 
> ```java
> public void asyncOpenLedger(final long lId, final DigestType digestType, final byte[] passwd,
>         final OpenCallback cb, final Object ctx) {
>     if (ledgerErrors.containsKey(lId)) {
>         cb.openComplete(ledgerErrors.get(lId), null, ctx);
>     } else {
>         super.asyncOpenLedger(lId, digestType, passwd, cb, ctx);
>     }
> }
> ```

Yes, doing an if else or adding a return is the way to truly solve the problem. Here are the test results:
﻿
![企业微信截图_17302657085370](https://github.com/user-attachments/assets/f49011fe-6a70-4425-aa3a-e8ccf7d34687)

2024-10-30 05:53 UTC, nodece approved these changes
LGTM

2024-10-30 14:19 UTC, lhotari commented on managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
> +            }else{
please use the default formatting code style that we use in Pulsar code base, [instructions for setting it up in IntelliJ](https://pulsar.apache.org/contribute/setup-ide/#configure-code-style).

2024-10-31 06:04 UTC, nodece commented on managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
> +            }else{
```suggestion
            } else {
```

Fix code style.

2024-11-05 08:19 UTC, lhotari approved these changes
LGTM, good work @ZhaoGuorui666. Thanks for putting effort in fixing flaky tests.

2024-11-05 10:16 UTC, merged