[fix][broker] fix metric for delayed memory occupation of sub.
apache/pulsar pull request #23712
Opened 2024-12-11 08:44 UTC by thetumbled

### Motivation

There is already one metric called `pulsar_delayed_message_index_size_bytes` for the total memory occupation used by delayed queue of **one topic**. 
Whereas, the metric for **one sub** also called `pulsar_delayed_message_index_size_bytes`, leading the miss of metric for sub.

### Modifications

Rename the metric for **one sub** to `pulsar_subscription_delayed_message_index_size_bytes`.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

2024-12-11 10:49 UTC, dao-jun commented
LGTM. However, since it changes the metrics name, I'm not sure if it is OK to merge the PR without a discussion.

2024-12-12 02:06 UTC, thetumbled commented
WDYT, @lhotari @coderzc

2024-12-12 07:53 UTC, lhotari commented
> Whereas, the metric for **one sub** also called `pulsar_delayed_message_index_size_bytes`, which do not comform the metric name norm and is confusing.

@thetumbled  Does this cause any problem other than it's not consistent with other subscription level metric name?

According to [our PIP guidelines](https://github.com/apache/pulsar/tree/master/pip#when-is-a-pip-required), changes like this require a PIP since it would be a breaking change in metrics. However, if this would be a bug where the metric wouldn't be usable at all, then a PIP wouldn't be required.

2024-12-12 08:24 UTC, thetumbled commented
> > Whereas, the metric for **one sub** also called `pulsar_delayed_message_index_size_bytes`, which do not comform the metric name norm and is confusing.
> 
> @thetumbled Does this cause any problem other than it's not consistent with other subscription level metric name?
> 
> According to [our PIP guidelines](https://github.com/apache/pulsar/tree/master/pip#when-is-a-pip-required), changes like this require a PIP since it would be a breaking change in metrics. However, if this would be a bug where the metric wouldn't be usable at all, then a PIP wouldn't be required.

Currently, it can export metric like:
```
# TYPE pulsar_delayed_message_index_size_bytes gauge
pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0"} 0
pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0",subscription="sub2"} 0
```

The metric of topic and subscription mix together. If we want to filter out the metric of sub to pick out the metric of topic, we need to use promsql like: 
`pulsar_delayed_message_index_size_bytes{subscription=""}`
It is quite weird and i believe that if any user use it already, he/she will contribute a pr to fix this, as these label names can only be access by researching the code, which means he/she is an advanced user and is involved in the community.

2024-12-12 16:28 UTC, lhotari commented
> Currently, it can export metric like:
> 
> ```
> # TYPE pulsar_delayed_message_index_size_bytes gauge
> pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0"} 0
> pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0",subscription="sub2"} 0
> ```
> 
> The metric of topic and subscription mix together. If we want to filter out the metric of sub to pick out the metric of topic, we need to use promsql like: `pulsar_delayed_message_index_size_bytes{subscription=""}` It is quite weird and i believe that if any user use it already, he/she will contribute a pr to fix this, as these label names can only be access by researching the code, which means he/she is an advanced user and is involved in the community probably.

@thetumbled Please add this directly to the description of this PR since it clarifies the issue. I'd suggest to start a discussion on that mailing list with these details. It's simplest to create a minimal PIP in any case to get this change documented.

2024-12-23 02:26 UTC, thetumbled commented
> > Currently, it can export metric like:
> > ```
> > # TYPE pulsar_delayed_message_index_size_bytes gauge
> > pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0"} 0
> > pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0",subscription="sub2"} 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The metric of topic and subscription mix together. If we want to filter out the metric of sub to pick out the metric of topic, we need to use promsql like: `pulsar_delayed_message_index_size_bytes{subscription=""}` It is quite weird and i believe that if any user use it already, he/she will contribute a pr to fix this, as these label names can only be access by researching the code, which means he/she is an advanced user and is involved in the community probably.
> 
> @thetumbled Please add this directly to the description of this PR since it clarifies the issue. I'd suggest to start a discussion on that mailing list with these details. It's simplest to create a minimal PIP in any case to get this change documented.

Sure, i will start one to discuss on this change.

2024-12-27 09:16 UTC, thetumbled commented
> > Currently, it can export metric like:
> > ```
> > # TYPE pulsar_delayed_message_index_size_bytes gauge
> > pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0"} 0
> > pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic="persistent://public/default/testNack-partition-0",subscription="sub2"} 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The metric of topic and subscription mix together. If we want to filter out the metric of sub to pick out the metric of topic, we need to use promsql like: `pulsar_delayed_message_index_size_bytes{subscription=""}` It is quite weird and i believe that if any user use it already, he/she will contribute a pr to fix this, as these label names can only be access by researching the code, which means he/she is an advanced user and is involved in the community probably.
> 
> @thetumbled Please add this directly to the description of this PR since it clarifies the issue. I'd suggest to start a discussion on that mailing list with these details. It's simplest to create a minimal PIP in any case to get this change documented.

I propose a pip to discuss on this change: https://github.com/apache/pulsar/pull/23789.

2025-01-13 06:18 UTC, thetumbled commented
The vote for pip passed , please review this pr again, thanks. @lhotari @dao-jun @BewareMyPower @poorbarcode @Shawyeok @nodece

2025-01-13 06:34 UTC, Shawyeok commented
LGTM

2025-01-13 06:39 UTC, Shawyeok requested changes
LGTM for the production code. However, you need to update the unit test `PersistentTopicTest#testDelayedDeliveryTrackerMemoryUsageMetric` to align with these changes.

2025-01-13 11:26 UTC, Shawyeok approved these changes
LGTM

2025-01-13 11:50 UTC, lhotari approved these changes

2025-01-14 07:12 UTC, dao-jun approved these changes

2025-01-14 09:40 UTC, merged