[fix] [ml] Topic load timeout due to ml data ledger future never finishes
apache/pulsar pull request #23772
Opened 2024-12-23 16:11 UTC by poorbarcode

### Motivation

**Background**
There is a mechanism that repeatedly prevents the callback of ML data ledger creation:
- Start a scheduled task to check whether the creation will be timeout.
- Received a callback
  - Check whether the future(`@param ctx` of `BK.createAsync`) has been done or not.
  - If done: it means the creation has timeout before the creation is completed
  - Otherwise: it is a real callback from BK.

**Issue:**
But the timeout event will call the same callback as above, then the steps are as follows, which you ca reproduce by the test `testCreateDataLedgerTimeout`:
- Start creating a data ledger
  - Call `BK.createAsync` 
- Timeout
  - Mark the future(`@param ctx` of `BK.createAsync`) as completed exceptionally. 
  - Trigger the callback related to ledger creation. 
    - Check whether the future(`@param ctx` of `BK.createAsync`) has been done or not.
    - If done: do nothing.
- Creation is compelled.
  - Trigger the callback related to ledger creation. 
    - Check whether the future(`@param ctx` of `BK.createAsync`) has been done or not.
    - If done: do nothing.
- Issue: The callback for ledger creation will never be called.

### Modifications

Fix the issue

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: x

2024-12-23 16:16 UTC, poorbarcode commented
/pulsarbot rerun-failure-checks

2024-12-24 04:59 UTC, nodece requested changes
It looks you should fix the `checkAndCompleteLedgerOpTask()`:
```java
    protected boolean checkAndCompleteLedgerOpTask(int rc, LedgerHandle lh, Object ctx) {
        if (ctx instanceof CompletableFuture) {
            // ledger-creation is already timed out and callback is already completed so, delete this ledger and return.
            if (((CompletableFuture) ctx).complete(lh)) {
                return false;
            } else {
                if (rc == BKException.Code.OK) {
                    log.warn("[{}]-{} ledger creation timed-out, deleting ledger", this.name, lh.getId());
                    asyncDeleteLedger(lh.getId(), DEFAULT_LEDGER_DELETE_RETRIES);
                    return true; // changed
                }
                return false; // changed
            }
        }
        return false;
    }
```

2024-12-24 04:59 UTC, nodece commented on testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java
> +        scheduler = Executors.newScheduledThreadPool(2, new DefaultThreadFactory("mock-bk-scheduler"));
```suggestion
        scheduler = Executors.newScheduledThreadPool(1, new DefaultThreadFactory("mock-bk-scheduler"));
```

2024-12-24 09:08 UTC, gaoran10 approved these changes

2024-12-24 12:32 UTC, shibd commented
> It looks you should fix the checkAndCompleteLedgerOpTask():

+1

2024-12-25 02:05 UTC, poorbarcode commented
@shibd @nodece 

> It looks you should fix the checkAndCompleteLedgerOpTask():

Good suggestion. Modified.

2024-12-25 02:13 UTC, nodece approved these changes

2024-12-25 02:50 UTC, dao-jun commented
> It looks you should fix the `checkAndCompleteLedgerOpTask()`:
> 
> ```java
>     protected boolean checkAndCompleteLedgerOpTask(int rc, LedgerHandle lh, Object ctx) {
>         if (ctx instanceof CompletableFuture) {
>             // ledger-creation is already timed out and callback is already completed so, delete this ledger and return.
>             if (((CompletableFuture) ctx).complete(lh)) {
>                 return false;
>             } else {
>                 if (rc == BKException.Code.OK) {
>                     log.warn("[{}]-{} ledger creation timed-out, deleting ledger", this.name, lh.getId());
>                     asyncDeleteLedger(lh.getId(), DEFAULT_LEDGER_DELETE_RETRIES);
>                     return true; // changed
>                 }
>                 return false; // changed
>             }
>         }
>         return false;
>     }
> ```

It seems no need to change here, the following steps will handle the case of `rc != OK`

2024-12-25 02:50 UTC, dao-jun approved these changes

2024-12-25 03:01 UTC, shibd approved these changes

2024-12-25 06:14 UTC, merged

2024-12-25 06:25 UTC, congbobo184 commented
> > It looks you should fix the `checkAndCompleteLedgerOpTask()`:
> > ```java
> >     protected boolean checkAndCompleteLedgerOpTask(int rc, LedgerHandle lh, Object ctx) {
> >         if (ctx instanceof CompletableFuture) {
> >             // ledger-creation is already timed out and callback is already completed so, delete this ledger and return.
> >             if (((CompletableFuture) ctx).complete(lh)) {
> >                 return false;
> >             } else {
> >                 if (rc == BKException.Code.OK) {
> >                     log.warn("[{}]-{} ledger creation timed-out, deleting ledger", this.name, lh.getId());
> >                     asyncDeleteLedger(lh.getId(), DEFAULT_LEDGER_DELETE_RETRIES);
> >                     return true; // changed
> >                 }
> >                 return false; // changed
> >             }
> >         }
> >         return false;
> >     }
> > ```
> 
> It seems no need to change here, the following steps will handle the case of `rc != OK`

+1