[WIP] Enable pulsar component to send their metrics to topics
apache/pulsar pull request #7433
Opened 2020-07-02 14:14 UTC by KannarFr

Fixes #7419

### Motivation

Enable pulsar components to send their metrics to defined topics in a dedicated tenant.

### Modifications

Create a MetricsSender interface and fill it with PulsarMetricsSender as the "to pulsar" sender.

### Verifying this change

This change added tests and can be verified as follows:

- tests are/will be defined in PulsarMetricsSenderTest

### Does this pull request potentially affect one of the following parts:

- configuration points to define interval & tenant to send.

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs
  - If a feature is not applicable for documentation, explain why? WIP

2020-07-02 14:16 UTC, KannarFr commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/sender/PulsarMetricsSender.java
> +            this.pulsar.getAdminClient().topics().createNonPartitionedTopic(topicToSend.toString());
@jiazhai @sijie what is the better way to manage tenant/ns/topic directly in pulsar code base? I'm currently using PulsarAdmin WDYT.

2020-07-02 14:17 UTC, KannarFr commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/sender/PulsarMetricsSender.java
> +}
Should we embed a retry with backoff stuff?

2020-07-02 14:19 UTC, KannarFr commented
I created the PR but it's currently a POC to get your opinions. Should we use schema using Metrics POJO?

2020-09-04 04:30 UTC, sijie requested changes
Why know just write an agent to collect the stats and write the stats to a Pulsar topic? It doesn't have to write such code at the broker side.

2020-09-04 09:06 UTC, KannarFr commented
@sijie pull-based collection require a more complex infra, but also for the monitored system to buffer data during polling. So when it's under load, you'll choose between eating memory or losing data. While in push, the data is out ASAP and the collector makes that decision. So push scales much better than poll particularly in the broker case where monitoring data increases with topics number.

WDYT?

2021-01-13 19:01 UTC, sijie commented
@KannarFr You can install a local agent per bookie to scrap the metrics from the local endpoint and push it to your metrics system. How is that different from adding a sender in Pulsar?

2021-01-25 12:52 UTC, closed without merging