[pulsar-functions] Fix message consume ordering issue of function
apache/pulsar pull request #8026
Opened 2020-09-10 06:46 UTC by Tiscs

Fix #7707
Fix message consume ordering issue of function with EFFECTIVELY_ONCE processing guarantees.

### Motivation

Since v2.5.2, function with EFFECTIVELY_ONCE processing guarantees consume message out of ordering when fail, because process a CompletableFuture result by async.

### Modifications

- Get result from future synchronized when processing guarantees of java instance equals `EFFECTIVELY_ONCE`.

2020-09-10 06:51 UTC, jiazhai approved these changes

2020-09-21 08:56 UTC, jiazhai commented
/pulsarbot run-failure-checks

2020-11-17 02:33 UTC, codelipenghui requested changes
Is it possible to add a unit test for this change? We don’t want other changes to break it.

2020-11-17 02:33 UTC, codelipenghui commented
move to 2.8.0 first.

2020-11-17 02:33 UTC, codelipenghui commented
@wolfstudy Please also help review this PR

2020-11-20 13:55 UTC, wolfstudy commented
@Tiscs Can you add test case for this change and rebase master branch?

2020-11-23 14:41 UTC, Tiscs commented
> @Tiscs Can you add test case for this change and rebase master branch?

Rebased, I'll add some cases later.

2021-05-19 07:07 UTC, codelipenghui commented
@Tiscs Could please rebase the master branch? There are related changes merged into the master branch.

2021-05-19 23:38 UTC, nlu90 commented
This PR might be a duplicate for this one: #10618

2021-05-21 07:28 UTC, codelipenghui commented
Sorry @Tiscs, we are merged #10618, and due to too long time this PR opened, we missed this one, thanks for the contribution. I will close this PR first and welcome to contribute more fixes and features in the Pulsar community.

2021-05-21 07:28 UTC, closed without merging

2021-05-21 10:11 UTC, Tiscs commented
> Sorry @Tiscs, we are merged #10618, and due to too long time this PR opened, we missed this one, thanks for the contribution. I will close this PR first and welcome to contribute more fixes and features in the Pulsar community.

Should the issue #7707 be closed?

2021-05-26 14:03 UTC, codelipenghui commented
@Tiscs Yes, it should be closed.