Subscription response implement
apache/pulsar pull request #8161
Opened 2020-09-29 14:27 UTC by congbobo184

## Motivation
- subscription response implement
- add the tracker for response timeout

## implement

### Verifying this change
Add the tests for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (yes)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

2020-09-30 07:59 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2020-09-30 14:32 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2020-10-07 11:14 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2020-10-08 03:45 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2020-10-11 07:48 UTC, codelipenghui commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
> +                bitSetRecyclable.set(0, batchMessageId.getAcker().getBatchSize());
The transaction message is a couple of batch messages, make sure can handle this well, @gaoran10 Please help double-check.

2020-10-11 07:48 UTC, codelipenghui commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
> +                bitSetRecyclable.set(0, batchMessageId.getAcker().getBatchSize());
Same as above comment.

2020-10-11 07:48 UTC, codelipenghui commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
> +                    .completeExceptionally(new TransactionConflictException("Consumer has closed!")));
The TransactionConflictException does not make sense here. It's better to add a MessageAcknowledgeException.

2020-10-11 07:48 UTC, codelipenghui commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
> +            log.error("Ack request has been handled requestId : {}", ackResponse.getRequestId());
Use info log level here

2020-10-11 07:48 UTC, codelipenghui commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
> +            callBackOp.callback.completeExceptionally(new TransactionConflictException(ackResponse.getMessage()));
We should get the specific exception from the `serverError`, should not be throw TransactionConflictException for all errors.

2020-10-11 07:48 UTC, codelipenghui commented on pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerAckResponseTest.java
> +import static org.mockito.Mockito.*;
Avoid use import .*

2020-10-11 07:48 UTC, codelipenghui commented on pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerAckResponseTest.java
> +            Assert.assertTrue(e.getCause() instanceof TransactionConflictException);
Why message id (1,1,1) conflict?

2020-10-11 08:18 UTC, eolivelli reviewed
It looks like this is a wire protocol change. Is this breaking compatibility with old servers and old clients?

2020-10-11 11:51 UTC, congbobo184 commented on pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerAckResponseTest.java
> +            Assert.assertTrue(e.getCause() instanceof TransactionConflictException);
ledgerId start with 3.

2020-10-12 04:50 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2020-10-12 07:48 UTC, eolivelli requested changes
Please state clearly if there are backward compatibility concerns.

In this case I think we should handle it, supporting old clients is a requisite, because we cannot require clients to be updated if you update only the broker.

cc @sijie @merlimat

2020-10-12 11:56 UTC, congbobo184 commented
@eolivelli I think added protocol fields are all optional type, so it doesn't need to think about compatibility.

2020-10-12 12:15 UTC, eolivelli commented
@congbobo184 is the new client able to work with Pulsar 2.6.1 ? it looks like it will expect an ack from the server now.
Probably is just only a matter of documenting better your change.

Can you please describe more this change in the description of the PR ?
- What is the problem that the PR is solving
- What is the design of the solution
- Compatibility with older clients and servers

2020-10-13 02:37 UTC, congbobo184 commented
@eolivelli This PR is for transaction ack and don't change any client API. In normal ack, we don't change any logical. I change the description of the PR.

2020-10-13 07:26 UTC, eolivelli commented
Thank you @congbobo184 
Now it is clear to me.

2020-10-14 02:49 UTC, codelipenghui commented on pulsar-common/src/main/proto/PulsarApi.proto
> +    TransactionConflictException = 23; // Ack with transaction conflict
```suggestion
    TransactionConflict = 23; // Transaction conflict
```

2020-10-14 04:06 UTC, codelipenghui approved these changes

2020-10-14 06:37 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2020-10-14 06:40 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2020-10-14 07:40 UTC, merged