[Issue 8260] Support reset cursor to a batch index of the batching message
apache/pulsar pull request #8285
Opened 2020-10-17 10:24 UTC by Renkai

Signed-off-by: Renkai <gaelookair@gmail.com>

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #8260

### Motivation

Make reset cursor command able to reset to a specific index in batch mode.

### Modifications

Now reset offset command change index info on broker side

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (yes / no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2020-10-18 09:59 UTC, Renkai commented
Still have some problem, unit test written by me can't be passed(due to timeout), 
https://github.com/apache/pulsar/pull/8285/files#diff-30ab326ad2d2e0d984b321af3c68c7bb7ab345fac245bbcc6739f58daffc0e68R120

Maybe there is some thing wrong with my test configuration
```
mvn -pl pulsar-broker -Dtest=SubscriptionSeekTest\#testSeekForBatch test -DredirectTestOutputToFile=false
```

PTAL @codelipenghui

2020-10-19 07:06 UTC, jiazhai commented
/pulsarbot run-failure-checks

2020-10-19 13:53 UTC, Renkai commented
/pulsarbot run-failure-checks

2020-10-20 00:03 UTC, codelipenghui commented
/pulsarbot run-failure-checks

2020-10-20 00:45 UTC, codelipenghui requested changes
I have double-checked the implementation of the `Batch Index Acknowledgment`. Looks we can only pass the `ackset` to the broker from the client-side, because currently `true` in the `BitSet` represent the message does not acked, and `false` means the batch index are acked. So I think it's the root cause of why the consumer start receive message from the next message of the reset position.

2020-10-20 00:45 UTC, codelipenghui commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
> +import java.util.*;
Avoid use import .* here.

2020-10-20 00:45 UTC, codelipenghui commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
> +import org.apache.pulsar.client.api.*;
Avoid use import .* here.

2020-10-20 00:45 UTC, codelipenghui commented on pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
> +        messageIdBuilder.setBatchIndex(batchIndex);
The `batchIndex` of the MessageIdData is an optional field, we shouldn't always use '0' here. It better to change the params type of the `batchIndex` to `Integer`. If the the `batchIndex` no a null value, set the value for the `MessageIdBuilder`

2020-10-20 00:45 UTC, codelipenghui commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
> +            ackSet.recycle();
It's better tot check `msgIdData.hasBatchIndex()` first, If the conditions are not met, we don't need to create the BitSet instance.

2020-10-20 04:18 UTC, Renkai commented
/pulsarbot run-failure-checks

2020-10-20 08:11 UTC, Renkai commented
/pulsarbot run-failure-checks

2020-10-21 01:29 UTC, wolfstudy commented
ping @codelipenghui PTAL again thanks.

2020-10-21 07:50 UTC, codelipenghui commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
> +        });
```suggestion
        FutureUtil.waitForAll(futureMessageIds).get()
```

2020-10-21 07:50 UTC, codelipenghui commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
> +        producer.flush();
Since the messageId is returned, we don't need to flush here.

2020-10-21 07:50 UTC, codelipenghui commented on pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
> +        assertEquals(nextMessage.getValue(), expectedMessage);
Could you please also add some corner case test? such as reset to the last message to check the consumer can't receive any message?

2020-10-21 09:13 UTC, codelipenghui approved these changes

2020-10-21 09:44 UTC, Renkai commented
/pulsarbot run-failure-checks

2020-10-21 11:16 UTC, merged

2020-10-22 03:06 UTC, codelipenghui commented
cherry-picked to branch-2.6(2.6.2)