[Transaction] Transaction pending ack persistent
apache/pulsar pull request #8881
Opened 2020-12-09 15:47 UTC by congbobo184

## Motivation
in order to handle pending ack persistent.

## implement
1. add the transaction pending ack store, it will handle the pending ack metadata store.
2. when the sub unload, we will replay the pendingAckHandle.
3. we use one manageLedger to store the pending ack metadata by one sub , and replay by this managedLedger open cursor.
4. when we commit or abort the transaction, we will append the marker to the pendingAckStore then we will modify state memory in pendingAckHandle
4. we also modify the in memory state when append fail, because we don't know the persistent state, when we replay it, it will produce the wrong operation. so we append fail, we should wait tc time out or client abort this transaction.
5. we use a timer task to delete the metadata, we judge whether the position of ack stored in metadata is less than the markDeletePosition of sub. when we read commit or abort marker, we can delete directly.
### Verifying this change
Add the tests for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

2021-01-15 08:06 UTC, eolivelli requested changes
this is a great work.
I believe this is a fundamental implementation in order to ship Transactions to the users

2021-01-15 08:06 UTC, eolivelli commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTimerTask.java
> +            if ("Cursor was already closed".equals(e.getCause().getMessage())) {
this is very error prone,
can we detect an instance of a specific class of exception ?

2021-03-05 01:07 UTC, codelipenghui commented
@gaoran10 Please help review this PR.

2021-03-17 01:13 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2021-03-17 09:14 UTC, congbobo184 commented
/pulsarbot run-failure-checks

2021-04-25 06:20 UTC, congbobo184 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckReplyCallBack.java
> +     * Handle metadata entry.
handle pending ack log. invoke as many times as there have entry have to be recover.

2021-04-25 06:24 UTC, congbobo184 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckReplyCallBack.java
> +    void replayComplete();
it can't fail, unless metadata is corrupted

2021-04-25 06:25 UTC, congbobo184 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/InMemoryPendingAckStore.java
> +        pendingAckHandle.changeToReadyState();
`InMemoryPendingAckStore.java` don't need replay.

2021-04-25 06:27 UTC, congbobo184 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStore.java
> +            outstandingReadsRequests.decrementAndGet();
read pending ack entry fail

2021-04-25 14:11 UTC, congbobo184 commented
@codelipenghui @eolivelli please review again. thanks.

2021-05-12 09:52 UTC, eolivelli approved these changes

2021-05-12 12:09 UTC, codelipenghui commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStore.java
> +    public static final String PENDING_ACK_STORE_SUFFIX = "__transaction_pendingack";
```suggestion
    public static final String PENDING_ACK_STORE_SUFFIX = "__transaction_pending_ack";
```

2021-05-12 12:24 UTC, congbobo184 commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
> +                    future.completeExceptionally(e);
the close is Is a synchronous method, so we should catch the exception.

2021-05-12 12:40 UTC, codelipenghui approved these changes

2021-05-13 04:21 UTC, merged