[ISSUE 8832] Avro custom schema not working in consumer
apache/pulsar pull request #8939
Opened 2020-12-12 15:56 UTC by reswqa

Fix #8832 

### Modifications
Make AvroSchema's clone method consider custom reader and writer.

2020-12-13 07:12 UTC, reswqa commented
/pulsarbot run-failure-checks

2020-12-13 08:48 UTC, eolivelli requested changes

2020-12-13 08:48 UTC, eolivelli commented on pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
> +        PulsarClient client =  PulsarClient.builder()
Please close this PulsarClient

2020-12-13 08:49 UTC, reswqa commented
/pulsarbot run-failure-checks

2020-12-13 09:00 UTC, reswqa commented on pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
> +        PulsarClient client =  PulsarClient.builder()
Thank you, it has been fixed.

2020-12-13 09:39 UTC, eolivelli approved these changes
Lgtm

@codelipenghui please consider a cherry pick to 2.6 and 2.7

2020-12-13 11:22 UTC, reswqa commented
/pulsarbot run-failure-checks

2020-12-13 17:56 UTC, sijie approved these changes

2020-12-14 00:11 UTC, codelipenghui approved these changes

2020-12-14 00:12 UTC, codelipenghui commented
@congbobo184 Could you please help take a loot at this PR?

2020-12-14 01:50 UTC, congbobo184 approved these changes
LGTM!

2020-12-14 04:22 UTC, merged

2020-12-21 11:09 UTC, codelipenghui commented
remove tag release 2.6.3 since it depends on https://github.com/apache/pulsar/pull/8464. There many conflicts with branch-2.6.