[Issue 9297][broker] Try to fix flaky infinite reconnection
apache/pulsar pull request #9298
Opened 2021-01-24 13:08 UTC by wuYin

Fixes #9297 

### Motivation

Try to fix flaky case which broker always returned unreachable address to client.

### Modifications

Before broker response lookup result, check the owner broker is active or not.
If not, remove the ownership, then redirect to leader broker to find a new active broker to own this bundle. 

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### Other
Since this case can't be reproduced easily, and this change will cause the lookup to increase the latency of the read local cache, so I'm not sure this is the best solution to fix this, if not, ok to close this PR.

2021-01-25 01:53 UTC, jiazhai approved these changes

2021-01-25 01:53 UTC, jiazhai commented
/pulsarbot run-failure-checks

2021-01-25 03:38 UTC, zymap commented
Looks like tests failed by this change:
```
Error:  Failures: 
Error:  org.apache.pulsar.broker.namespace.OwnershipCacheTest.testGetOwner(org.apache.pulsar.broker.namespace.OwnershipCacheTest)
[INFO]   Run 1: PASS
Error:    Run 2: OwnershipCacheTest.testGetOwner:202 ? Execution java.lang.NullPointerException
[INFO] 
Error:  org.apache.pulsar.broker.namespace.OwnershipCacheTest.testReestablishOwnership(org.apache.pulsar.broker.namespace.OwnershipCacheTest)
[INFO]   Run 1: PASS
Error:    Run 2: OwnershipCacheTest.testReestablishOwnership:354 ? Execution java.lang.NullPoin...
[INFO] 
Error:    TransactionMetaStoreAssignmentTest.init:34->TransactionMetaStoreTestBase.setup:53 ? SessionExpired
[INFO] 
Error:  Tests run: 499, Failures: 3, Errors: 0, Skipped: 1
```

2021-01-25 04:09 UTC, wuYin commented
@zymap thanks for review
Actually, I'm not sure this ownership double check PR will solve the flaky Issue
I'll add test to simulate flaky case by removing the /loadbalance/downBroker zNode directly, and fix existed failure tests

2021-01-25 09:35 UTC, jiazhai commented
@wuYin this change lgtm. the latency for read local zk cache should be fine. Otherwise it would be hard to fix this issue. 
It would be great to add a test to cover and protect this change.

2021-01-25 21:32 UTC, sijie approved these changes

2021-01-27 01:25 UTC, codelipenghui approved these changes

2021-01-27 01:28 UTC, jiazhai commented
/pulsarbot run-failure-checks

2021-03-08 22:17 UTC, sijie commented
/pulsarbot run-failure-checks

2021-06-01 14:21 UTC, codelipenghui commented
@wuYin Could you please help check the failed tests? I have moved it to 2.9.0 and tag `release/2.8.1`, if the test passed, we can move it back to 2.8.0

2021-08-05 03:41 UTC, hangc0276 commented
@wuYin  Would you please address the conflict? i am starting to release 2.8.1, it all tests passed, we can include this pr in 2.8.1

2021-08-10 03:19 UTC, hangc0276 commented
@wuYin Could you please help check the failed tests and the conflicts?  I have moved it to  tag release/2.8.2,  if the test passed and conflict addressed, we can move it back to 2.8.1.

2021-08-10 07:35 UTC, eolivelli requested changes

2021-08-10 07:35 UTC, eolivelli commented on pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
> +                        removeOwnership(suName);
here we are in `getOwnerAsync` that is meant to be free from side effects.

I am not sure this is the right fix

2021-11-01 10:03 UTC, 315157973 commented
@wuYin  Hello, please take a look at eolivelli's comments

2021-11-01 11:21 UTC, closed without merging