[Issue 9480][pulsar-io] add option for auto.offset.reset to kafka source
apache/pulsar pull request #9482
Opened 2021-02-04 13:50 UTC by sbourkeostk

Fixes #9480 

### Motivation

The kafka source sets auto.offset.reset to "earliest". This means all old messages from kafka are produced to pulsar. Often is it desirable to start form the present location "latest".
The option is set after the user config has been loaded so it cannot be changed:
[source code link](https://github.com/apache/pulsar/blob/master/pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java#L87)

### Modifications

Added an autoOffsetReset option to KafkaSourceConfig

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests and can be verified as follows:
Added to unit test and verified behaviour.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs / JavaDocs
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2021-02-04 13:52 UTC, sbourkeostk commented on site2/docs/adaptors-kafka.md
> -| `auto.offset.reset`                     | Yes       | Will have a default value of `latest` if user does not give specific setting. |
This is a correction to an error in the existing docs.

2021-02-04 15:00 UTC, Renkai commented
@BewareMyPower Could you have a look?

2021-02-04 15:10 UTC, codelipenghui approved these changes

2021-02-04 15:11 UTC, BewareMyPower requested changes
Could you add the sample config to `kafkaSourceConfig.yaml` and verify it in `loadFromYamlFileTest`?

2021-02-04 16:41 UTC, sbourkeostk commented
Sample config added to kafkaSourceConfig.yaml and verified in loadFromYamlFileTest

2021-02-05 00:57 UTC, BewareMyPower approved these changes

2021-02-05 02:21 UTC, Anonymitaet commented on site2/docs/adaptors-kafka.md
> +| `auto.offset.reset`                     | Yes       | Will have a default value of `earliest` if user does not give specific setting. |
```suggestion
| `auto.offset.reset`                     | Yes       | It uses a default value of `earliest` if you do not give a specific setting. |
```
In technical information, follow these general guidelines for personal pronouns:
• Avoid the first-person pronouns I and we, except in these situations:
° In the question portion of frequently asked questions (FAQs)
° In articles, white papers, or documents that have listed authors and in which the authors describe their own actions or opinions
• Use the second-person pronoun you as much as possible. The subject of an imperative sentence is understood to be you.
• Avoid third-person pronouns that are gender specific.

2021-02-05 05:20 UTC, sijie approved these changes

2021-02-05 07:43 UTC, Anonymitaet approved these changes

2021-02-05 07:57 UTC, eolivelli approved these changes
LGTM

2021-02-05 13:27 UTC, sbourkeostk commented
/pulsarbot rerun-failure-checks

2021-02-08 09:40 UTC, sbourkeostk commented
/pulsarbot rerun-failure-checks

2021-02-08 14:56 UTC, 315157973 approved these changes

2021-02-12 00:18 UTC, jiazhai approved these changes

2021-02-12 09:49 UTC, sbourkeostk commented
/pulsarbot rerun-failure-checks

2021-02-12 22:24 UTC, sbourkeostk commented
/pulsarbot rerun-failure-checks

2021-02-15 05:06 UTC, merged