Disable negativeAck for Key_Shared sub type.
apache/pulsar pull request #9583
Opened 2021-02-14 08:43 UTC by MarvinCai

Fixes #9582

### Motivation
The message negative ack will break the message ordering dispatch guarantee, Key_Shared is an ordering dispatch guarantee subscription, so we should avoid the message negative ack for the Key_Shared subscription.

### Modifications
Check if it's Key_Shared subscription type before negativeAcking messages.

### Verifying this change

This change added tests and can be verified as follows:
  - *Added test case.*

2021-02-14 11:57 UTC, eolivelli requested changes

2021-02-14 11:57 UTC, eolivelli commented on pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
> +                log.debug("NegativeAcknowledge for Key_Shared subscription type for message {} is ignored as this will" +
Why aren't we throwing an error?

2021-02-14 20:00 UTC, merlimat requested changes
I'm not convinced this is the the right thing here, for a couple of reasons: 

 1. The negative acks also work for Exclusive and Failover subscriptions, which are also ordered.
 2. The key shared is not only used for strictly ordered data. The ordering can already be relaxed in use cases when you want to have stickiness of data to consumers, without the need for strict ordering within a key.

I see this more as a documentation issue perhaps, where user should be aware that negative acks are going to trigger the out of order delivery of a particular message.

Even then, it would still be possible to have messages go to DLQ after the first failure, thus retaining ordering in the consumer, while using negative-ack.

2021-02-16 02:36 UTC, codelipenghui commented
@merlimat 

I'm not sure how `the negative acks also work for Exclusive and Failover subscriptions, which are also ordered` works, from the source code, seems nothing different for the negative ack between different subscription types. For sequential processing, the application usually processes the next message after one message is successfully processed. So the application should retry the failed message until processed successfully.

Currently, users can use the strictly ordered guarantee and allow out of order. I think If users enabled the out of order option, they can use the DLQ/nack, but for the strictly ordered guarantee, we should avoid the DLQ and nack.

2021-02-16 16:23 UTC, merlimat commented
My point of comparison was that it doesn't make sense to disable for key-shared when it's allowed for exclusive and failover.

The bigger point here is that the exclusiveness is not only done with the purpose of ordering (both for exclusive, failover as well as for key-shared type).

2021-02-22 14:44 UTC, codelipenghui commented
I see, thanks for the explanation. So for the DLQ and negative ack, we can allow to enable them for all subscription types but if the purpose is ordering, we should not use DLQ and negative ack.

2021-02-23 04:34 UTC, MarvinCai commented
As discussed, closing this pr, will have another pr to update document for negative ack/DLQ for ordered sub type.

2021-02-23 04:34 UTC, closed without merging