#9986 [functions] - Allow Disabling of Function Batching
apache/pulsar pull request #9987
Opened 2021-03-20 08:19 UTC by devinbost

### Motivation
This PR creates a workaround for #6054 that should enable users who are experiencing that issue to be able to upgrade to more recent versions of Pulsar while the underlying problem is continuing to be worked on. 

### Modifications
I added a default function batching setting to WorkerConfig that affects defaults cluster-wide. I also added the ability to override that default setting on a per-function basis by adding a FunctionBatching enum to the Protobuf function definition. I used an enum because protobuf does not allow null boolean values, and I didn't want a default value on the function definition to prevent functionality of the cluster-wide setting. So, the enum allows an UNKNOWN value to be set (which basically is the equivalent of a null), and when that value is UNKNOWN, the behavior is to use the cluster-wide setting (which defaults to `true` to prevent creating breaking changes.)

I created a couple of tests, but I'd like some guidance on additional test coverage. 

Fixes #9986

### Verifying this change

This change is already covered by existing tests:
- Many tests already touch WorkerConfig and FunctionDetails. What else needs to be tested in this PR?

This change added tests and can be verified as follows:
  - *Added test that checks for `UNKNOWN` ProducerSpec value*
  - [Need guidance on how to test other parts of behavior]

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (yes, users can set new parameter when deploying function)
  - The schema: (don't know)
  - The default values of configurations: (no)
  - The wire protocol: (**yes**) (added property to protobuf definition of function)
  - The rest endpoints: (no)
  - The admin cli options: (not sure)
  - Anything that affects deployment: (don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (not documented)
  - If a feature is not applicable for documentation, explain why? (urgently needs to be rolled out)
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2021-03-20 08:21 UTC, devinbost commented
I'd like help with getting this included in the release of Pulsar 2.8.0. 
@jerrypeng @sijie @codelipenghui @lhotari @rdhabalia

2021-03-20 08:52 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-03-20 12:02 UTC, lhotari commented
/pulsarbot run-failure-checks

2021-03-20 12:35 UTC, eolivelli commented
I am not sure I understand if this fix is resolving your problem or it is only a mitigation.

2021-03-21 02:24 UTC, devinbost commented
> I am not sure I understand if this fix is resolving your problem or it is only a mitigation.

It's only a mitigation for now, but it's still a useful feature for anyone who wants to disable function message batching for any other reason.

2021-03-22 04:16 UTC, jerrypeng commented on pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
> +    private boolean isFunctionBatchingEnabledDefault = true;
This seems like a one-off config as in the there are no other configs in worker configs that define defaults for certain function configs.  If we are going to let cluster admin set defaults for function configs at a cluster level, we should do it in a more comprehensive manner and not just have one-off configs like this.

2021-03-22 04:20 UTC, jerrypeng requested changes
Will I am in favor of allowing users to configure whether functions should enable batching or not.  I am not in favor of creating a "default" config for the enabling batching in worker config.  This seems like a one-off thing as worker config currently does not define defaults for other function configs.  I am in favor of creating a way for cluster admins to be able to define defaults for certain function configs at a cluster level, but it needs to be a more comprehensive mechanism and not just one-off configs.

2021-03-22 07:34 UTC, devinbost commented
> Will I am in favor of allowing users to configure whether functions should enable batching or not. I am not in favor of creating a "default" config for the enabling batching in worker config. This seems like a one-off thing as worker config currently does not define defaults for other function configs. I am in favor of creating a way for cluster admins to be able to define defaults for certain function configs at a cluster level, but it needs to be a more comprehensive mechanism and not just one-off configs.

Thanks for the feedback. I appreciate your review. What would that more comprehensive mechanism look like to you? Would the defaults still go into WorkerConfig?
We could populate an object with additional default settings, but we'd need a way to map each default setting to a destination, which could be a method call (such as when building the function producer) or a property set (such as on a function config). Since there's a lot of variation in how those defaults might need to be applied, it's not clear to me how that should be done in a general way. Perhaps we could use reflection to lookup what needs to be set or called at runtime (for applying a particular default), but that would increase the risk of user problems at startup.

2021-03-22 20:28 UTC, devinbost commented
One of the challenges is that protobuf doesn't support null primitives, so it's not as simple as just checking the function config for a null and then using the corresponding WorkerConfig default if the function config property is null. If we just rely on the function config's default value for the default behavior, then there's no way for a cluster admin to change all the functions' behavior with one config change. (Instead, every function would need to be re-deployed.) 

I suppose I could create a new kind of ProducerBuilder (such as ProducerBuilderWithDefaults) that would be passed an object with the Function defaults and the WorkerConfig's function defaults, and it would provide the logic for each builder method to check the Function default, and if it's set to the protobuf default value, then it assumes the Function default was equivalent to "null" and then uses the corresponding property on the object with the WorkerConfig's function defaults. 

With that said, it doesn't look like each producer implementation uses pulsar.getProducerBuilder()... some of them use client.newProducer(..) (such as in PulsarSink, https://github.com/apache/pulsar/blob/master/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java#L110), but I'm not sure we want to expose all that to the client.

2021-03-22 22:14 UTC, devinbost commented
It looks like I can use the loadConf method on ProducerBuilderImpl (https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerBuilderImpl.java#L121), so that might be cleaner than needing to decorate the ProducerBuilder with one that has builder methods that set defaults.

2021-03-23 04:58 UTC, jerrypeng commented
@devinbost in WorkerConfig, we can add a new field call defaultFunctionConfig/defaultSourceConfig/defaultSinkConfig or defaultFunctionConfigFile/defaultSourceConfigFile/defaultSinkConfigFile if we just want to point to a separate file. 

In the worker config could look something like

```

workerId: standalone
workerHostname: localhost
...
defaultFunctionConfig:
  producerConfig: 
    maxPendingMessages: 100
    enableBatching: true
```

On registering the function, we merge the user provided function config with the default function config.

2021-03-24 22:25 UTC, devinbost commented
/pulsarbot run-failure-checks

2021-03-25 17:45 UTC, devinbost commented
/pulsarbot run-failure-checks

2021-03-25 23:53 UTC, devinbost commented
/pulsarbot run-failure-checks

2021-03-26 01:32 UTC, devinbost commented
I have not been able to reproduce these test failures locally. Additional eyes would be helpful.

2021-03-26 02:18 UTC, devinbost commented
/pulsarbot run-failure-checks

2021-03-26 03:12 UTC, devinbost commented
/pulsarbot run-failure-checks

2021-04-28 17:47 UTC, closed without merging